### ISSUE TITLE
Start9 / EmbassyOS integration

### ISSUE THREAD

**Issue by secondl1ght** [joinmarket-webui/jam#117]
I reached out to the Start9 team to see if they are interested in adding the joinmarket-webui to their marketplace. It sounds like they are interested and will be adding it sometime this year!

Link to issue: https://github.com/Start9Labs/embassy-os/issues/1237

**Comment by dnlggr** [comment]
Awesome, thanks for tracking this here! Let's keep this issue open in case we need to discuss anything related to the integration on our end.
