### ISSUE TITLE
Orderbook parsing

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#14]
As discussed in [Call 2](https://github.com/joinmarket-webui/joinmarket-webui/wiki/community-call-%232), it would be interesting to do some automatic parsing of the orderbook to let the user choose sane defaults instead of fiddling with various fee settings. 

Not sure if it's feasible or easily possible, so consider this an idea more than a feature that has to be implemented. 

Listen to the call recording and have a look at the [JM orderbook docs](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/orderbook.md) and an [online orderbook](https://nixbitcoin.org/orderbook/) to get an idea of what data is in the orderbook and what settings could be automatically set or hidden from the user.

**Comment by Richie-BTC-Rich** [comment]
On the earn tab a link to the marketplace https://nixbitcoin.org/orderbook/refreshorderbook would be a helpful resource to determine fees before starting the service.  After the service is running a a link to the marketplace  with your Counterparty ID would be helpful so you can verify your offer is listed.
