### ISSUE TITLE
dev: Regtest user personas

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#189]
As discussed in Community Call 11, it would greatly improve development experience, if there were some "used" wallets representing different scenarios. This will make testing certain use cases manually much more comfortable and less time consuming.

List of characters:
- e.g. "alice": A for the first char; i.e Alice is a pristine user that just created a wallet
- e.g. "bob": B for the second char; i.e. Bob has a single utxo in the wallet
- e.g. "frank": F for Fidelity Bond; i.e. Frank ran tumbler and created a fidelity bond
- [...]
- e.g. "mary": M for Maker; i.e. Mary  just wants to be a maker; does not care about privacy
- e.g. "ted": T for Taker; i.e. Ted just wants to be a taker; cares deeply about privacy
- [...] 
- e.g. "zoey": Z for the last char; i.e. Zoey completed the cheatsheet step by step

Add the scenario you'd like to exist when starting the regtest environment, name it and post it here: See [List of Characters Wiki Page](https://en.wikipedia.org/wiki/Alice_and_Bob#Cast_of_characters) as inspiration.

As a first step, a wallet that has completed the tumbler once would already be nice. So
- [ ] alice
- [ ] bob
- [ ] frank

should be enough to start.
What do you think? Anything else you started noticing doing over and over again, while working with the dev environment?

**Comment by theborakompanioni** [comment]
This call is perhaps relevant to be able to assess whether and how much of it is actually needed: https://github.com/BitcoinDesign/Meta/issues/324

**Comment by dnlggr** [comment]
Yeah that would be nice. We can build that incrementally. One concern: I don't want to wait for a whole tumbler run to setup the regtest environment. Resource heavy personas need to be manually enabled somehow.

**Comment by theborakompanioni** [comment]
I am closing this as it seems not really important for the now. Reopen on demand!
