### ISSUE TITLE
Ability to stop a running taker operation

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#269]
The only way to stop a running taker operation is to lock the wallet – that is not so intuitive.

At least in regtest, `Makers who didnt respond` can happen quite often. Should the possibility to stop a single taker operation be considered? In the meantime, the workaround works fine.

**Comment by theborakompanioni** [comment]
Related https://github.com/joinmarket-webui/joinmarket-webui/issues/155

**Comment by editwentyone** [comment]
something like this? https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/?node-id=3283%3A85776

<img width="698" alt="image" src="https://user-images.githubusercontent.com/96262473/169146333-6c40313b-9739-4609-8f84-4beabaa9a13e.png">

**Comment by dnlggr** [comment]
Looks good. I also like what you did with the tabs in that screenshot. 👌✨

**Comment by dnlggr** [comment]
An issue we currently have is that we cannot differentiate on the client between the a single collaborative transaction and a schedule of collaborative transactions running. This makes it impossible to treat a single collaborative transaction (Send) and the scheduler (Jam) differently -- therefore anytime either of them is "active" UI-wise, the other one needs to be as well. So we can show a "Stop" button on the send page but it will also show when the scheduler is running, which is weird.

I will check with the backend and see if we can get separate "running" flags for the scheduler and a single collaborative transaction. That will make things a lot easier:

- Correctly showing the activity indicator. Currently the "Jam" tab is showing indicating activity when a single collaborative transaction is running
- Showing a stop button on the Send page only when a single collaborative transaction is running
- Blurring the Send page only when the scheduler is running
- ...

**Comment by theborakompanioni** [comment]
>  So we can show a "Stop" button on the send page but it will also show when the scheduler is running, which is weird.

Can it be distinguished by checking if an API call to `/schedule` returns `404` or `200`?
- If `taker_running := true` and `/schedule` responds with `404`: Send is active.
- If `taker_running := true` and `/schedule` responds with `200`: Scheduler is active.

**Comment by dnlggr** [comment]
That's a nice hack. 😉 I think we can get a flag into the `/session` endpoint quite easily though. I'm already on it. If that doesn't play out for some reason we can still fall back to what you described I'd say.

**Comment by dnlggr** [comment]
Relevant backend PR that would enable us to differentiate between "Schedule" and "Single Collaborative Transaction": https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1307

**Comment by theborakompanioni** [comment]
As https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1307 has been merged, this issue is unblocked and can be worked on.

**Comment by dergigi** [comment]
Tempted to pump this up to 0.1 or at least 0.1.1 - super annoying that you can't stop a running operation yet.

Should be as easy as calling [/taker/stop](https://joinmarket-org.github.io/joinmarket-clientserver/api/#operation/stopcoinjoin)
