### ISSUE TITLE
Refactor `CreateFidelityBond` component in TypeScript

### ISSUE THREAD

**Issue by ghost** [joinmarket-webui/jam#364]
There's some messy and repetitive parts in `CreateFidelityBond.jsx`. When we find time we can refactor it and use TypeScript to do so.

**Comment by theborakompanioni** [comment]
`CreateFidelityBond.jsx` is already converted to typescript, however, it's still a candidate for refactoring.
I'd say, this can and should be done during #650, so I am closing this issue now.
Feel free to reopen, if you think this is a mistake.
