### ISSUE TITLE
Intermediate collaborative tx before funding fidelity bond

### ISSUE THREAD

**Issue by ghost** [joinmarket-webui/jam#367]
See discussion in the [community call #18](https://github.com/joinmarket-webui/joinmarket-webui/wiki/community-call-%2318).

We might want to consider doing a collaborative tx to an address in the same mixdepth before funding a fidelity bond to de-link the UTXOs involved from their history before they go into the fidelity bond.

**Comment by editwentyone** [comment]
not planned to be implemented, enough best practices are communicated
