### ISSUE TITLE
Back button for fidelity bond flow

### ISSUE THREAD

**Issue by ghost** [joinmarket-webui/jam#370]
Currently we have a "cancel" button shown on each step that allows you to abort the whole flow. A "back" button to go back one step would be more useful here.

**Comment by editwentyone** [comment]
with the redesign of the complete flow, everything should be better usable. its divided in steps and you can go back and reopen a step to make changes, please see: https://github.com/joinmarket-webui/jam/issues/372#issuecomment-1383009458

**Comment by theborakompanioni** [comment]
Closing this in favor of https://github.com/joinmarket-webui/jam/issues/650
