### ISSUE TITLE
Q: Display confirm modal before initiating transaction?

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#385]
Should a confirm modal be displayed, similar to the one when creating a fidelity bond or locking a wallet when a service is running, before a transaction is initiated (`POST` to `/direct-send` or `/taker/coinjoin`)?

Rational is that a user gets the chance to review a summary and potentially catch any input errors.
It is an action triggering an event which should definitely not have data with typos or other unintended values.
What do you think?

**Comment by editwentyone** [comment]
as a quick win: modal 
for a better flow: summary

**Comment by theborakompanioni** [comment]
Question is primarily whether a modal should be presented in the first place. @editwentyone I suppose a summary in the modal is okay UX wise, yes?
