### ISSUE TITLE
Show total Fidelity Bond duration in addition to expiration date

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#397]
Now:

> ... the fidelity bond expires on Tue, 01 Nov 2022 00:00:00 GMT

Better:

> ... the fidelity bond expires on Tuesday, Nov 1st (in 15 weeks and 6 days).

**Comment by ABHISHEK-PANDEY2** [comment]
*My first time solving a issue Please do give feedbacks*


we can use timestamp of the date the bond is getting over and subtract it with current timestamp to get the remaining time left 
and then convert it to weeks and days
let us take an example of exp date being tue 1 nov 2022.

`function bondExpiryStr(bondExpDate){`
`const expDate = new Date(bondExpDate);`
`const expTimeStamp = expDate.getTime();`
`const remTimeStamp = expTimeStamp - Date.now();`

`const convertToString = function(remainingTime){`
`const days = remainingTime/(1000*60*60*24);`
`const remWeeks = Math.floor(days/7);`
`const remDays = Math.floor(days - remWeeks * 7);`
``const str = `${remWeeks} weeks and ${remDays} days`;``
`return str; }`

`const expiryString = function(){`
`const dateStr = expDate.toDateString();`
`const dateStrArr = dateStr.split(' ');`
``const exprDateStr = `the fidelity bond expires on ${dateStrArr[0]}, ${dateStrArr[1]} ${dateStrArr[2]} (in ${convertToString(remTimeStamp)})`;``
`return exprDateStr; }`
`return expiryString(); }`

`bondExpiryStr('tue 1 nov 2022');`

**Comment by ABHISHEK-PANDEY2** [comment]
output of the above code 

`the fidelity bond expires on Tue, Nov 01 (in 15 weeks and 4 days)`

**Comment by dnlggr** [comment]
Awesome @ABHISHEK-PANDEY2, thanks for contributing! If you want, feel free [to open a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) that integrates your code. That makes it easy for us to review and test it. See also [CONTRIBUTIN.md](https://github.com/joinmarket-webui/joinmarket-webui/blob/master/CONTRIBUTING.md) for more info.

Let me know if you need help with the process.

**Comment by ABHISHEK-PANDEY2** [comment]
I was trying to set the repo in my local host 

but could not understand what to do about this
" Start the JoinMarket HTTP API service in regtest: "
docker-compose --file docker/regtest/docker-compose.yml up
like where to run this command
