### ISSUE TITLE
Earn: show offer and fee settings when earn is active

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#399]
There is no way to tell what fees you've set when earn is active. You would have to stop the maker service.

All we show currently is this:

![Screenshot 2022-07-14 at 08 36 55](https://user-images.githubusercontent.com/109058/178916955-f2648ba5-cf69-4b27-9ad5-dd744d2abc43.png)

I imagine something like the following would be useful:

> Offering a minimum amount of 100,000 sats at a 0.03% fee.

or, when the offer is absolute

> Offering a minimum amount of 100,000 sats at a 250 sat fee.

---

Basically show whatever was set here:

![Screenshot 2022-07-14 at 08 34 11](https://user-images.githubusercontent.com/109058/178916787-bdccf2ff-48bc-4441-88f8-031ed6190293.png)

**Comment by theborakompanioni** [comment]
This is currently not possible within the current api functionality.
A workaround like saving it to local storage, won't give reliable results if users change browsers.
Will open a ticket in the backend repo shortly.

**Comment by dnlggr** [comment]
Blocking this issue. If possible, please link the backend issue @theborakompanioni, I couldn't find it myself. 🤔

**Comment by theborakompanioni** [comment]
> Blocking this issue. If possible, please link the backend issue @theborakompanioni, I couldn't find it myself. thinking

Thanks for reminding me.. here it is: ["Current maker offer/counterparty via RPC API #1326"](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1326)

**Comment by dnlggr** [comment]
Removing this from v0.0.10 and moving to v0.1.0 as I don't think we'll get a working solution in the next couple of days.

**Comment by theborakompanioni** [comment]
This is unblocked when https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1328 is merged.
