### ISSUE TITLE
Earn: Link to local orderbook

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#412]
Raised by @Richie-BTC-Rich in #14:

> On the earn tab a link to the [orderbook] would be a helpful resource to determine fees before starting the service. 

---

Local orderbook instance should be accessible via http://localhost:62601/

**Comment by theborakompanioni** [comment]
Hmm.. imho, we should try to implement https://github.com/joinmarket-webui/joinmarket-webui/issues/14 instead (or in addition).
It is basically done and at least the styling can be controlled and subsequently beautified. What do you think?

**Comment by dergigi** [comment]
Nice! That's even better! 💖

**Comment by dnlggr** [comment]
See https://github.com/joinmarket-webui/jam/issues/14.
