### ISSUE TITLE
Question: start jar numbering at 1?

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#416]
Currently, the default of 5 jars is displayed as follows:

- `Jar #0`
- `Jar #1`
- `Jar #2`
- `Jar #3`
- `Jar #4`

While this is in accordance to JoinMarket internals, and fine for nerds and computer science people, it's probably confusing for newcomers. 

Question: should we use the more natural numbering of 1 to 5?

- `Jar #1`
- `Jar #2`
- `Jar #3`
- `Jar #4`
- `Jar #5`

I'm talking about a change in the user-facing UI only, internally numbering will start at zero, of course.

**Comment by dnlggr** [comment]
Definitely start at 1! 👍 

We just have to be careful to not confuse our UI indexes with the actual ones. Sweeping the forth (zero-indexed) jar when the user actually wanted to sweep the third one would be bad. 😅

**Comment by dergigi** [comment]
> Every now and than you need to go back to the cli

That might be true now, but I hope that it won't be true in the future. Hmm. 🤔

**Comment by dnlggr** [comment]
Closing this in favor of #435.
