### ISSUE TITLE
Concept: named jars (orange, strawberry, etc.)

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#435]
As discussed in [Community Call 20](https://github.com/joinmarket-webui/joinmarket-webui/wiki/community-call-%2320). Related to #416.

---

2022-07-04: Updated suggestion, again from `Jar 0` to `Jar 4`:

* A = Apricot 🟠
* B = Blueberry 🔵
* C = Cherry 🔴
* D = Date 🟤
* E = Elderberry 🟣

Benefit: Nicely maps 0-1-2-3-4 to A-B-C-D-E, removing the "nerd numbering" that starts with zero, without introducing additional confusion that would arise from switching to 1-2-3-4-5 (because JoinMarket still uses 0-1-2-3-4).

---

Previous suggestion, from `Jar 0` to `Jar 4`:

* Orange 🟠
* Strawberry 🔴
* Grape 🟢
* Blueberry 🔵
* Plum 🟣 

Fruits are picked randomly, somwhat.[^fn-jams] (Tried to pick some that would map nicely to colors. Color accents should be very subtle, if present at all, to not confuse users with 'green is good' or 'red is bad'.)

[^fn-jams]: https://www.statista.com/statistics/280744/us-households-most-eaten-flavors-of-jams-jellies-and-preserves-trend/

**Comment by dergigi** [comment]
Added an updated suggestion to use A-B-C-D-E instead of numbers.

**Comment by dnlggr** [comment]
Letters instead of numbers are great! Gets rid of the awkward 0-index while keeping the mapping to the number-indexed mixdepths on the CLI reasonable.

Quick mockup just to help people visualize it:

<img width="600" alt="Screenshot 2022-08-04 at 11 39 33" src="https://user-images.githubusercontent.com/10026790/182816253-c654425e-2f31-426d-82c1-a78315d79ccf.png">

Obviously we'd have to find a nicely looking color scheme. This is just something quick from [coolors.co](https://coolors.co/e8871e-26547c-bf0603-dbbea1-932f6d).

**Comment by editwentyone** [comment]
with this api we could more or less randomize it even https://colornames.org/download/
example: https://colornames.org/search/results/?type=exact&query=plum

**Comment by dergigi** [comment]
We had some more discussions on this in [Call 21](https://github.com/joinmarket-webui/jam/wiki/Community-Call-%2321). Unless someone objects, I feel like we should strive to include this in v0.1. 

I will update [the docs](https://jamdocs.org/glossary/#jar) accordingly, and unless there are volunteers I'm happy to implement this myself.

**Comment by dnlggr** [comment]
Sounds good! I'm not so sure about making the colors random, though. I feel like that might be confusing and make it harder to memorize which Jar is which.

**Comment by dergigi** [comment]
Agree! No randomness required.

**Comment by dnlggr** [comment]
Would you be able to come up with a nicely looking color scheme @editwentyone?

**Comment by editwentyone** [comment]
not yet, are we already fixe with the names? 

Apricot
Blueberry
Cherry
Date
Elderberry

or are there other suggestions?

**Comment by editwentyone** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/96262473/184339992-b1bc73b4-cf19-45d7-8df3-26dcbfc11465.png">

https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=4367%3A113433

**Comment by editwentyone** [comment]
Darkmode: 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/96262473/184340404-8ecc6453-89bd-4b54-8a4d-ef14db13ee49.png">

https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=5072%3A61903

**Comment by editwentyone** [comment]
what do you think @dnlggr ? "Date" in darkmode is possibly to red, but I think its ok to start with

**Comment by dergigi** [comment]
Nice, I like it!

I agree @editwentyone that `Date` is a bit too red when on black, and `Blueberry` and `Elderberry` might also be too close together. I'll see if I can get to implementing this before v0.1 and might play around with the colors a bit. 🎨 🧑‍🎨

**Comment by editwentyone** [comment]
I updated the dark mode version again, see here https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=5072%3A61903

<img width="692" alt="image" src="https://user-images.githubusercontent.com/96262473/185404588-0bd36992-f6ee-41c4-bb2c-a3f2589c1311.png">

**Comment by dergigi** [comment]
Adjusted the colors slightly, made the `Date` one a bit more brown and the `Elderberry` one a bit more violet-ish. 

Let me know what you think!

![image](https://user-images.githubusercontent.com/109058/185422275-2ac8b6cb-eadd-46af-ba2a-c0a37d74c759.png)

See #476
