### ISSUE TITLE
Remove advanced mode

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/jam#441]
Once https://github.com/joinmarket-webui/jam/pull/430 is merged, we're feature complete in a way that we can remove the "Developer/Advanced" mode we had until now.

**Comment by theborakompanioni** [comment]
Is this targeting the whole "developer mode" flag, or just harmonizing the diverging views ("CurrentWalletMagic" and "CurrentWalletAdvanced")?

There is an upcoming feature regarding better user feedback by adding the ability to view the raw `jmwalletd` log.. would it make sense to keep the toggle and show this new functionality only for users activating the `developer mode`?

**Comment by dnlggr** [comment]
No I don't think we need a dedicated developer mode. If someone wants to view the logs, they should be able to access the logs. There's no benefit to hide them in a developer mode that first needs to be toggled imo. This is similar to how we now also show "advanced" settings e.g. on the Earn screen without first needing to toggle some global advanced mode.
