### ISSUE TITLE
Improve Jar Details View

### ISSUE THREAD

**Issue by ghost** [joinmarket-webui/jam#444]
The Jar details view needs some care. At the very least it needs to be adapted to look good on all screen sizes and be consistent with the UTXO list. Maybe a little design refresh wouldn't hurt either but that's optional for now.

There's some comments on what needs to be done in https://github.com/joinmarket-webui/jam/pull/430.

<img width="1361" alt="Screenshot 2022-08-03 at 10 26 51" src="https://user-images.githubusercontent.com/10026790/182561799-a0392234-53ec-489e-a00c-20d245d35c7c.png">

**Comment by editwentyone** [comment]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/96262473/184351193-1702a69d-d03f-487b-ab90-d8784951eaca.png">

https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=4139%3A77309

**Comment by dergigi** [comment]
Resolved with #430, remaining issues tracked as #480
