### ISSUE TITLE
Remove "keep funds in Jam" from scheduler

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#481]
As discussed in [Call 22](https://github.com/joinmarket-webui/jam/wiki/Community-Call-%2322).

- [x] Remove option to "keep funds in Jam"
- [x] User has to enter external addresses manually
- [ ] Question: show warning if internal address is used via manual copy-paste?

**Comment by theborakompanioni** [comment]
>     * [ ]  Question: show warning if internal address is used via manual copy-paste?

Voting for "Yes". Would also prevent scheduler from starting, tbh.
But there is only so much we can do.. if a user generates addresses from an xpub, which are not yet "known" to jm,.. this cannot (reasonably) be prevented (and probably shouldn't).

Do you think this is the right time to introduce client-side address validation?
I think (need to verify!) that JM does this too but there is no immediate response when starting the scheduler (it subsequently fails silently).

**Comment by dergigi** [comment]
> Would also prevent scheduler from starting, tbh.

Not sure about that one.

**Comment by theborakompanioni** [comment]
Should a warning still be displayed if an "internal" addresses is used?
