### ISSUE TITLE
`npm audit` shows 6 high severity vulnerabilities with current master

### ISSUE THREAD

**Issue by kristapsk** [joinmarket-webui/jam#503]
Current master (commit 89b04a18c651aa2b4fd4ed33fa3baf4af2cea428).

This should be fixed before v0.1.0 release.
```
$ npm audit
# npm audit report

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@2.1.3, which is a breaking change
node_modules/css-select/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          node_modules/react-scripts

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by theborakompanioni** [comment]
Hey @kristapsk, thanks for the report.

I am little confused as npm seems to suggest downgrading `react-scripts` from `v5.0.1` (most recent version) to `v2.1.3`.
As far as I am aware:
> [...] it explains that the attack vector is via network, but this is a build-time dependency that doesn't exist in built apps

(from https://github.com/facebook/create-react-app/issues/11647#issuecomment-1243863292)

There are multiple issues in the upstream repo already. I guess waiting for an update is the way to go.
I'd close this as with "won't fix" if that is okay with you.

**Comment by theborakompanioni** [comment]
Looked into it. Nothing with high severity regarding to Jam.

> If you [read the description](https://github.com/advisories/GHSA-rp65-9cf3-cjxr), it explains that the attack vector is via network, but this is a build-time dependency that doesn't exist in built apps (the only dependency of a CRA app after build is React itself). As explained in https://github.com/facebook/create-react-app/issues/11174 we will not be addressing fake vulnerabilities.

Inclined to close this issue soon.

**Comment by kristapsk** [comment]
It's always simpler to just upgrade than analyze specific vulnerabilities, but if there is problems with doing that and you are sure it doesn't affect Jam in any way, it's ok to close.
