### ISSUE TITLE
Send: Hide "number of collaborators" behind send options

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#508]
As of now, we have "receive options" for the receive screen, but no "send options" for the send screen.

Two things can be set:
* Collaborative transaction (default = true)
* Number of collaborators (default = 9)

I guess these defaults are fine for most people, and could be hidden behind collapsible options, just like we have it on the receive screen.

**Comment by editwentyone** [comment]
[🎨 Figma](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=4433%3A81973&viewport=-1567%2C-3208%2C0.59)

<img width="502" alt="image" src="https://user-images.githubusercontent.com/96262473/197946488-0e9b4460-57fa-4f13-8a02-15b4eb229543.png">

**Comment by theborakompanioni** [comment]
Closed by #595
