### ISSUE TITLE
ui: improve header of JarDetailsOverlay

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#528]
Header of `JarDetailsOverlay` component can be visually improved and should be aligned with the Figma copy.
Figma: https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI

## :camera_flash: Before/Current

<img src="https://user-images.githubusercontent.com/3358649/193567398-962ea0ee-9982-41bf-8d23-289900ddb8c6.png" width=600 />

## :camera_flash: After
<img src="https://user-images.githubusercontent.com/3358649/193567447-264fd3b4-a927-4df0-a552-7b97f1b67441.png" width=600 />

**Comment by Jared-Dahlke** [comment]
@theborakompanioni how does this look?

light mode:
![image](https://user-images.githubusercontent.com/32936978/210836220-1f14b736-2568-47e5-83f6-842e48e42a7c.png)

dark mode:
![image](https://user-images.githubusercontent.com/32936978/210836116-e338d269-05d8-44c1-bf80-c92d8996f07a.png)

I think the tabs need a new styling for dark mode when they are on the lighter color bg, but I don't see a figma for that. Was thinking about adding a new prop to <SegmentedTabs/>  to accamodate this

**Comment by theborakompanioni** [comment]
> @theborakompanioni how does this look?

Great :orange_heart: 
 
> I think the tabs need a new styling for dark mode when they are on the lighter color bg, but I don't see a figma for that. Was thinking about adding a new prop to to accamodate this

Yeah, what about adapting the background color in dark mode e.g. matching the darker color of the table? We can further discuss in the PR. Just try and take what you feel fits best for now.
