### ISSUE TITLE
python3 jmwalletd.py - OpenSSL Error

### ISSUE THREAD

**Issue by gianlock** [joinmarket-webui/jam#539]
Hi, 
following the steps for the manual installation, after successfully installed JoinMarket, i receive an error when I execute 
`python3 jmwalletd.py `

Here what I receive:
`User data location: /home/user/.joinmarket/`
`2022-10-09 00:30:07,669 [INFO]  Starting jmwalletd on port: 28183`
`Traceback (most recent call last):`
  `File "jmwalletd.py", line 47, in <module>`
    `jmwalletd_main()`
  `File "jmwalletd.py", line 39, in jmwalletd_main`
    `jm_wallet_daemon.startService()`
  `File "/home/user/joinmarket-clientserver-0.9.8/jmclient/jmclient/wallet_rpc.py", line 230, in startService`
    `cf = get_ssl_context(os.path.join(jm_single().datadir, "ssl"))`
  `File "/home/user/joinmarket-clientserver-0.9.8/jmclient/jmclient/wallet_rpc.py", line 116, in get_ssl_context`
    `return ssl.DefaultOpenSSLContextFactory(os.path.join(cert_directory, "key.pem"),`
  `File "/home/user/joinmarket-clientserver-0.9.8/jmvenv/lib/python3.8/site-packages/twisted/internet/ssl.py", line 111, in __init__`
    `self.cacheContext()`
  `File "/home/user/joinmarket-clientserver-0.9.8/jmvenv/lib/python3.8/site-packages/twisted/internet/ssl.py", line 119, in cacheContext`
    `ctx.use_certificate_file(self.certificateFileName)`
  `File "/home/user/joinmarket-clientserver-0.9.8/jmvenv/lib/python3.8/site-packages/OpenSSL/SSL.py", line 907, in use_certificate_file`
    `_raise_current_error()`
  `File "/home/user/joinmarket-clientserver-0.9.8/jmvenv/lib/python3.8/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue`
    `raise exception_type(errors)`
`OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'file_ctrl', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]`

**Comment by theborakompanioni** [comment]
Hey! Thanks for the heads-up. It seems the Jam docs miss information about generating a self-sign ssl certificate.
It is [mentioned in the docs (section "how to start the server")](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/v0.9.8/docs/JSON-RPC-API-using-jmwalletd.md#introduction---how-to-start-the-server), albeit not very prominent.
Will make sure to include

Please generate a ssl certificate and try starting the server again.
In your data dir (e.g. `~/.joinmarket/`), execute the following:
```sh
mkdir ssl/ && cd "$_"
openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out cert.pem -keyout key.pem -subj "/C=US/ST=Utah/L=Lehi/O=Your Company, Inc./OU=IT/CN=example.com"
```
(taken from the [Jam standalone docker image setup script](https://github.com/joinmarket-webui/jam-docker/blob/v0.1.1-clientserver-v0.9.8/standalone/jam-entrypoint.sh#L27-L34))

Please also make sure to provide values for config variables `max_cj_fee_abs` and `max_cj_fee_rel` in your `joinmarket.cfg`.
e.g. the Jam setup will randomize them, "absolute max fee" to a value between 5000 - 10000 sats; "relative max fee" to 0.0001, 0.0002 or 0.0003 (0.01% - 0.03%). But of course, you can change it to your own needs.

Hope this solves your issue. I will make sure to include some info in the Jam docs. Thank you!

**Comment by theborakompanioni** [comment]
Hey @gianlock, please let us know if that solved your issue. :pray:

**Comment by gianlock** [comment]
Hey @theborakompanioni I confirm I solved the issue. Thank you so much!
I'll read the docs more carefully :)
