### ISSUE TITLE
Transifex Language Addition

### ISSUE THREAD

**Issue by readmor** [joinmarket-webui/jam#541]
Hey I will work on Turkish but needs to be accepted as a new language on Transifex.
Cheers.

**Comment by theborakompanioni** [comment]
@readmor nice! Accepted! Thanks! :orange_heart: 
Please know that Jam is very early stage and some language keys are very likely to change :grimacing:

**Comment by theborakompanioni** [comment]
Closing this as the language is accepted and the translation can be worked on now.
Please reopen if you need anything related to this issue.
