### ISSUE TITLE
feat: spend fidelity bond

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#547]
**Is your feature request related to a problem? Please describe.**
If a wallet contains an **expired** fidelity bond, as soon as it is **unfrozen**, no other action than direct-sends (maker/taker operation) are possible anymore from Jar A (where the FB resides).

**Describe the solution you'd like**
A concrete way to ~~renew or~~ spend the FB without unfreezing it manually via the UI.
Prevent FBs from being unfrozen after they expire, but let it be used via distinct actions, e.g. "Move to jar"~~/"Renew"~~ -> See screenshots.

**Describe alternatives you've considered**
All alternatives that come to mind involve several manual steps by a user, which feels unnecessarily complicated.

**Additional context**
<img src="https://user-images.githubusercontent.com/3358649/196885718-5be11740-02f6-4496-90f0-aed006438032.png" width=400 />

**Comment by dergigi** [comment]
I guess this can be closed as #556 got merged? 

If "renew" is still a priority I'd say we create a new issue.

**Comment by theborakompanioni** [comment]
Resolved by #556.
