### ISSUE TITLE
Have a "DO COINJOIN" button?

### ISSUE THREAD

**Issue by alexwaltz** [joinmarket-webui/jam#562]
_I would like to clarify that I used JoinMarket before using JAM, so my opinion may be tainted by this somewhat._

The 1st thing I wanted to do while trying the app for the 1st time was to make a CJ in the simplest way, but I spent about 3 minutes trying to find the option.
Finally, I found it under "**Send as collaborative transaction**"

I can see why the option resides under the Send tab, after all, you are _sending_ Bitcoin from a jar/mixdepth to another one so technically is very accurate, however, I find it incredibly counter-intuitive.

I also(personally) find the term "collaborative transaction" vague and non-descriptive, I mean a LN channel open/close, coinswap or any mulit-sig can be a collaborative TXs.

Is this a CoinJoin app, or a collaborative transaction app?
The terms are really not synonymous, the 1st one is more narrow and specific.

_______
Arguments against it 

While the purpose of the app is to make things easier and faster, at the end of the day this is software that moves money around in a non-reversible way and if there is a place to measure `n` times and cut once this is it.

So maybe the option of having to easy to access is not a good idea.

Similar to how the red important button in a nuclear reactor requires one to open a box and turn a key before you press it(at least in movies it does) maybe the same tactic should be employed here.

**Comment by theborakompanioni** [comment]
Hey @alexwaltz, thanks for your inputs and the time to write them down.

I think this has been extensively discussed [in early community calls](https://github.com/joinmarket-webui/jam/wiki/community-calls). Once you've done it one or two times from the `Send` page, you'll get familiar with it and it'll be much more natural.

You are completely right with your assessment, though! However, changing the terminology now leads to massive changes, both to how the UI is structured, as well as to the documentation. In the future, Jam might also include PayJoins and opening Lightning channels, so it might get significant in the future again.

I'll close this issue now. Feel free to reopen it, if you think this should still be discussed further.
e.g. you can bring it up in the next Community Call! Or, if you are a designer, a few hints on look & feel in the [Figma screens](https://github.com/joinmarket-webui/jam/wiki/Figma) are highly appreciated.
