### ISSUE TITLE
API errors

### ISSUE THREAD

**Issue by Buttafuoco** [joinmarket-webui/jam#571]
**Expected behavior**
Login via Web - Local Network

**Actual behavior**
No connection to backend: Gateway Timeout.

**Steps to reproduce the problem**
  1. Start the jam daemon
  2. Open the web local page https://192.168.x.x:4020
  3. Skip the introduction

**Specifications**
  - Version: 0.1.3
  - Platform: Debian GNU/Linux 11 (bullseye) 
  - Browser: Firefox on Linux Mint 20.3 Una

**Additional context**
Journalctl jam constantly print this:

 [HPM] Error occurred while proxying request 192.168.x.x:4020/api/v1/session to https://localhost:28183/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)

and less frequently:

[HPM] Upgrading to WebSocket

**Comment by theborakompanioni** [comment]
Hey @Buttafuoco and @nu5h4ckle! Nice to see efforts to integrate Jam in RaspiBolt :muscle: 

I can only guess and from reading the linked pull request, I think it may be due to the reverse proxy configuration. e.g. see the config used in the `ui-only` docker image: https://github.com/joinmarket-webui/jam-docker/blob/master/ui-only/nginx/templates/default.conf.template

Especially note that endpoints `/api` and `/jmws` are proxied to `jmwalletd`, and `/obwatch` to `ob-watcher`.

Anyway, let me know if you have further questions or issues. Happy to help in any way.

**Comment by Buttafuoco** [comment]
> 

Hi @nu5h4ckle thanks for the answer

The journalctl of Jmwalletd service print this error when starting:

File "/home/joinmarket/joinmarket-clientserver-0.9.8/scripts/jmwalletd.py", line 47, in <module>
  jmwalletd_main()

File "/home/joinmarket/joinmarket-clientserver-0.9.8/scripts/jmwalletd.py", line 39, in jmwalletd_main
  jm_wallet_daemon.startService()

File "/home/joinmarket/joinmarket-clientserver-0.9.8/jmclient/jmclient/wallet_rpc.py", line 230, in startService
  cf = get_ssl_context(os.path.join(jm_single().datadir, "ssl"))

File "/home/joinmarket/joinmarket-clientserver-0.9.8/jmclient/jmclient/wallet_rpc.py", line 116, in get_ssl_context
 return ssl.DefaultOpenSSLContextFactory(os.path.join(cert_directory, "key.pem")

File "/home/joinmarket/joinmarket-clientserver-0.9.8/jmvenv/lib/python3.9/site-packages/twisted/internet/ssl.py", line 111, in __init__
 self.cacheContext()

File "/home/joinmarket/joinmarket-clientserver-0.9.8/jmvenv/lib/python3.9/site-packages/twisted/internet/ssl.py", line 119, in cacheContext  
 ctx.use_certificate_file(self.certificateFileName)

File "/home/joinmarket/joinmarket-clientserver-0.9.8/jmvenv/lib/python3.9/site-packages/OpenSSL/SSL.py", line 907, in use_certificate_file 
 _raise_current_error()

File "/home/joinmarket/joinmarket-clientserver-0.9.8/jmvenv/lib/python3.9/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue 
 raise exception_type(errors)

**OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'file_ctrl', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]**

for the certificate i have created a self signed cert. in a ssl directory under home folder with

$ mkdir ssl/ && cd "$_"

$ **openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes \
  -out cert.pem -keyout key.pem \
  -subj "/C=US/ST=Utah/L=Lehi/O=Your Company, Inc./OU=IT/CN=example.com"**

@theborakompanioni 
the reverse proxy configuration under the streams.enabled/jam-reverse-proxy.config is:

**upstream jam {
  server 127.0.0.1:3020;
}
server {
  listen 4020 ssl;
  proxy_pass jam;
}**

thanks for helping me

**Comment by theborakompanioni** [comment]
> **OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'file_ctrl', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]**
> 
> for the certificate i have created a self signed cert. in a ssl directory under home folder with

The `ssl` folder must be created in JM's working directory -> `/home/<user>/.joinmarket/ssl/`.

```sh
user@regtest:~/.joinmarket/ssl $ pwd
/home/user/.joinmarket/ssl

user@regtest:~/.joinmarket/ssl $ ls -l
total 8
-rw-r--r-- 1 user user 1789 Nov 23  2022 cert.pem
-rw------- 1 user user 3272 Nov  23  2022 key.pem
```
> 
> @theborakompanioni the reverse proxy configuration under the streams.enabled/jam-reverse-proxy.config is:
> 
> **upstream jam { server 127.0.0.1:3020; } server { listen 4020 ssl; proxy_pass jam; }**

Ahh,.. now I see.. you are running Jam by executing `npm start`. This should generally work "without" reverse proxy (as it is proxied by the npm setup scripts) - but it is generally "not advised". Better would be to build the static pages (`npm run build`) and put a reverse proxy in between. Let's do that after you were able run it successfully with the current approach.
I am not sure, but I still think the websocket path needs to be explicitly proxied. Let's see.

**Comment by Buttafuoco** [comment]
> > **OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'file_ctrl', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]**
> > for the certificate i have created a self signed cert. in a ssl directory under home folder with
> 
> The `ssl` folder must be created in JM's working directory -> `/home/<user>/.joinmarket/ssl/`.
> 
> ```shell
> user@regtest:~/.joinmarket/ssl $ pwd
> /home/user/.joinmarket/ssl
> 
> user@regtest:~/.joinmarket/ssl $ ls -l
> total 8
> -rw-r--r-- 1 user user 1789 Nov 23  2022 cert.pem
> -rw------- 1 user user 3272 Nov  23  2022 key.pem
> ```
> 
> > @theborakompanioni the reverse proxy configuration under the streams.enabled/jam-reverse-proxy.config is:
> > **upstream jam { server 127.0.0.1:3020; } server { listen 4020 ssl; proxy_pass jam; }**
> 
> Ahh,.. now I see.. you are running Jam by executing `npm start`. This should generally work "without" reverse proxy (as it is proxied by the npm setup scripts) - but it is generally "not advised". Better would be to build the static pages (`npm run build`) and put a reverse proxy in between. Let's do that after you were able run it successfully with the current approach. I am not sure, but I still think the websocket path needs to be explicitly proxied. Let's see.

Changing the directory has worked! thank you for your time!

is it more secure to approach with npm run build? at the moment the only way to see the page is with proxy at port 4020
i thin is out of my possibilities to do as you say, but i'm trying to understand

**Comment by theborakompanioni** [comment]
> Changing the directory has worked! thank you for your time!

Nice. I am happy it worked! :muscle: 

> is it more secure to approach with npm run build? at the moment the only way to see the page is with proxy at port 4020 i thin is out of my possibilities to do as you say, but i'm trying to understand

Hmm.. I would not say "more secure".. using it the way you are describing is generally more convenient, so probably not as bad as I thought at first. I have to think about it a little more deeply. This approach might change in the future, but I guess it is okay for now, if you are pinning the version/tag. However, that can also be said for the static page + reverse proxy - which is also more work on your side. So I think there are benefits and drawbacks in both approaches. Do whatever you think fits best for your use-case!

Have  a great day!

I am closing the issue now - feel free to reopen if you have further questions or comments!
