### ISSUE TITLE
feat: Verify that every user wrote down their seed phrase

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#577]
**Is your feature request related to a problem? Please describe.**

Currently a user can skip the seed phrase confirmation by reloading the page after a wallet is created.

**Describe the solution you'd like**

It should be verified that - no matter what - that the user wrote down the seed phrase.

**Describe alternatives you've considered**

The alternative is that a user might not have written down the seed phrase and is at risk at losing funds.
Which basically means: There is currently no alternative other than forcing the user to write down the seed.

**Additional context**

After creating a wallet a user will be asked to confirm the seed.
If the user (accidentally) reloads the page, a prompt will appear that asks: 
> This page is asking you to confirm that you want to leave — information you've entered may not be saved

However, a user can decide to reload anyway, in which case the wallet is created and Jam never verifies that the seed was written down.

A possible solution is to save the successful confirmation of a seed to local storage (per wallet).
However, this would mean that Jam needs to reconfirm the seed when browser data is deleted or browsers are switched (might be annoying...).
If you can think of other (read: better) solutions than this: Please state them as a comment here!

<img src="https://user-images.githubusercontent.com/3358649/207875592-6eeae072-bd2f-4e42-bfb9-71bae6413c60.png" width=300 />

**Comment by editwentyone** [comment]
I thought we had a confirmation page? https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=3754%3A73346&t=jXaHwHPykBPXLYJC-11

should be unskipable and on every reload, or back / forth its randomizing the 6 fields: so you have to write it down to confirm.

**Comment by theborakompanioni** [comment]
Hey @edi.. 

1. Yes, there is already a confirmation page, but there is no check if it is completed successfully. e.g. a user reloads the page? -> the wallet is already created an can be unlocked normally without the "quiz" being completed. 
2. Wasn't there consensus to always ask for the full seed phrase, as otherwise it's not verified that everything is backed up correctly? If not, personally, I would advocate for doing that.
3. As Jam is just a UI, there is no way to store information permanently. If the fact that the quiz was completed is stored to local storage, this info will be removed whenever browser data is cleared. Exactly like with the "onboarding" screen. Meaning, the quiz will be shown again and again for privacy minded users (which exactly is Jam's user base). The very noble attempt to make a user complete the quiz will likely become a security nightmare by making them keeping it in a not-so-hidden location or worse, in an unencrypted texfile, just to be able to input it whenever Jam asks them to. This does not sound like something Jam should do, tbh.

I am sorry I cannot propose a proper solution to this currently. Needs more thinking.

**Comment by editwentyone** [comment]
@theborakompanioni thanks for clearing things up again.
1. got it
2. you are right, lets keep it the way it is.
3. sound even worse

you are right, more thinking is needed. on the one hand, we don't want to annoy people and on the other hand we already had some failures in the chat, where people just think they are smarter until lightning strikes and the hard drive is toast… 

we could implement more annoying steps like: 
- you want to do your first CJ? please enter word 7 to continue.
- you want to create a FB? please enter word 12 to continue + [ ] don't bother me again.
- you want to tumble the wallet? please enter word 3 to continue + [ ] don't bother me again.
- we are not asking anymore.

**Comment by editwentyone** [comment]
sure, i dont think thats important right now and users understand the importance here.
