### ISSUE TITLE
Select utxos on send

### ISSUE THREAD

**Issue by greenart7c3** [joinmarket-webui/jam#580]
There should be an option to select which utxos I wish to spend

**Comment by theborakompanioni** [comment]
Sounds nice.. a dedicated modal to select UTXOs from the Send page would be a great enhancement.

**Comment by editwentyone** [comment]
if we implement the new FB creation dialog, we could also reuse parts of the flow for the send screen

**Comment by editwentyone** [comment]
will be tackled with #689
