### ISSUE TITLE
Trying to run this locally and getting error when i run "npm run regtest:up"

### ISSUE THREAD

**Issue by Jared-Dahlke** [joinmarket-webui/jam#581]
Hey I'm mostly a UI developer trying to run this locally to see how I can contribute.
I followed the steps on https://github.com/joinmarket-webui/jam/blob/master/CONTRIBUTING.md , but when i get to `npm run regtest:up` , I see this error:
![image](https://user-images.githubusercontent.com/32936978/209992488-1c855972-1ef3-44c1-a859-cc1f0a540d30.png)

Anybody know why this may be?

**Comment by theborakompanioni** [comment]
Hey @Jared-Dahlke, thanks for the heads-up.
Indeed.. I could reproduce this behaviour when trying to rebuild the setup. 
Investigating!

**Comment by theborakompanioni** [comment]
Seems to be introduced with https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1396
In the dev environment, JM is built from the current master branch on purpose, so it is somewhat expected/accepted that things might break from time to time. Should be mitigated with https://github.com/joinmarket-webui/jam/pull/585 - would be able to try if that fixes the problem for you?

**Comment by Jared-Dahlke** [comment]
@theborakompanioni hmm for some reason I'm unable to checkout this branch. Will keep trying for a bit

**Comment by Jared-Dahlke** [comment]
@theborakompanioni I was able to just go in and change the 2 lines from your commit manually, now it seems to be working! Thank you for the help!
