### ISSUE TITLE
Send: 5 confs warning is shown after success, which is confusing

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#596]
Feedback from [Giacomo's students](https://t.me/JoinMarketWebUI/6112):

> No serious bug to report, no serious UX confusion either (except maybe that, after a cooperative send, the error-like alert about "5 confs being necessary to send cooperatively" confused some of them a bit, since it seemed the send had failed, when it has succeded...probably a success message would help).

We could change the warning to an info or something like that, if a send was just successfully made. The warning is more important for first-time users, i.e. for the first send.

**Comment by editwentyone** [comment]
Already tackled here https://github.com/joinmarket-webui/jam/issues/516#issuecomment-1382865893 waiting for development. 

Bens Tutorial already brought it to light. But good that it’s coming up more, we are on the right path

**Comment by theborakompanioni** [comment]
I think this can be closed.

1) A success message is shown after a transaction has been made.
2) Jars are not preselected anymore (so the message is only shown, after a jar has been chosen).

What do you say @editwentyone ?

**Comment by editwentyone** [comment]
exactly, closing it
