### ISSUE TITLE
Created a Fidelity Bond but "Start Earning" returns "Maker could not start, no confirmed coins."

### ISSUE THREAD

**Issue by KainerW** [joinmarket-webui/jam#597]
I Created a Fidelity Bond but the button at the bottom "start earning" returns "Maker could not start, no confirmed coins." at the top of the Earn page.

If there is a problem - a way to fix it or at least some infos around the problem would be better here. 

**Actual behavior**

**Steps to reproduce the problem**
  1. Send bitcoin to wallet
  2. Use Earn - Created a Fidelity Bond
  3. Press "start earning"

**Specifications**
  - Version: raspiblitz 1.9.0
  - Platform: raspberry pi 
  - Browser: firefox

**Additional context**

Error-Message on page (after pressing button "start earning) "Maker could not start, no confirmed coins." does not give any information on how to fix. There are def confirmed coins in my wallet and the coins are even confirmed in a Fidelity Bond as shown on same page.

Trying to get more infos (e.g. looking into the order book if my fidelity bond is active/existing there) returned nothing (could not find anything related to my bond in the order book...)

Is it a bug? Not really I guess but it is just confusing to present "Maker could not start, no confirmed coins." while my fidelity bond is active and shown on same page.

After creating the fidelity bond... do I have to press "start earning" or is this button only for users without fidelity bond?

**Comment by PulpCattel** [comment]
> There are def confirmed coins in my wallet and the coins are even confirmed in a Fidelity Bond as shown on same page.

Do you have other coins other than the bond?
Fidelity bonds are timelocked on the Bitcoin blockchain, and **cannot** be spent in any way until the timelock expires. You need some other coins, other then the fidelity bond.

See the documentation:
* https://jamdocs.org/interface/fidelity-bonds/
* https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/fidelity-bonds.md

> It is impossible to move or spend funds that are locked in a fidelity bond before the bond expires. They cannot be used in collaborative transactions as fidelity bonds are time-locked by the Bitcoin protocol.

**Comment by KainerW** [comment]
Thank you PC, I did in fact just understand that wrong.

**Comment by theborakompanioni** [comment]
This is indeed a UX problem that must be addressed. Thanks for reporting.

**Comment by editwentyone** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/96262473/215142613-a5475811-ce67-43de-96a6-64953e8d21d2.png">

https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=5604%3A67014&t=sIEGlehebAvdIjb1-11

we poured already some thoughts into this problem, please review and give feedback of any kind. hope it helps.

**Comment by wchancao** [comment]
@editwentyone Hi, I have the same "problem", so, reading the image you sent, i need to send more coins to another jar if i want to start earning? Why another jar and not the one where the fidelity bond was created?

**Comment by editwentyone** [comment]
I think (just my 2 sats) it doesn't really matter if you re-send it to the same jar, I'm not sure about privacy implications, just use a fresh receiving address

**Comment by theborakompanioni** [comment]
Closing this as the next release will have a warning message that should make it more obvious (for users that have not read the docs about Fidelity Bonds). Reopen on demand.

## :camera_flash: 

<img src="https://github.com/joinmarket-webui/jam/assets/3358649/f079552e-e5e7-43c2-935d-947a5a9a9e05" height=450 />
<img src="https://github.com/joinmarket-webui/jam/assets/3358649/74ed23c7-b274-435b-80b6-b58dc0fe7f62" height=450 />
