### ISSUE TITLE
Display spendable balance on send page 

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#598]
From the chat:

> When a jar has less sats than you are trying to spend it let's you attempt the spend and then quietly fails.  It took me a few tries to figure out what was going on.  Normally this would be obvious, but in the case of jar with the FB it shows the amount of sats including the FB.  Leading me to think they were all available to spend.  

> I think a warning to let you know that you don't have sufficient funds(unlocked/unfrozen) for the proposed spend would fix this.

This has been talked about before, but there is no ticket yet.
It is confusing to show the total balance of a jar, when in fact some UTXOs are frozen or time-locked.
How can this best be displayed and communicated to the user?

**Comment by 86codyharris** [comment]
I think leaving the total amount(includes frozen&FB utxos) in the Jars view is ok.  Would it be possible to just change the amount in the **Send>Send From** drop down menu to reflect "spendable coins"?  This way you shouldn't have payment failures due to trying to spend frozen/FB coins  If a user notices a difference in balance from the Jar to the **Send From** tab they can go back into the Jar and see that it is the frozen/FB coins that have been subtracted.

**Comment by theborakompanioni** [comment]
> Would it be possible to just change the amount in the **Send>Send From** drop down menu to reflect "spendable coins"? 

Yeah, good idea. However, in the current draft of the send page the dropdown menu is replaced by a jar selector.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/96262473/212487164-b0dc20fa-9cb4-421d-87e6-e599cd719d04.png">

You are right, showing only the spendable balance is already an improvement. Additionally, by adding a way to quickly open a coin control modal (#580) , this might actually not be a horrible UX after all.. :-)

**Comment by editwentyone** [comment]
we could adapt this new screen to "spendable amounts" and with a "look inside" you open up a modal or something in this context on the send screen,  will think about it

**Comment by theborakompanioni** [comment]
> we could adapt this new screen to "spendable amounts" and with a "look inside" you open up a modal or something in this context on the send screen, will think about it

:100: 

In #600 the spendable amount is already shown. I like the idea of opening the details view exactly like in the main view. However, it will be done in a follow-up PR, if that is okay with you @editwentyone

**Comment by editwentyone** [comment]
sure it is, thank you :)
