### ISSUE TITLE
Import wallet through seedphase

### ISSUE THREAD

**Issue by Berlelund** [joinmarket-webui/jam#607]
There is no option to import a wallet via seedphase. 
I use Jam through a node and the starting page's only option is to create a new wallet but no option to restore/import a wallet with BIP-39 seedphases.

**Comment by theborakompanioni** [comment]
Hey @Berlelund, thanks for the feature suggestion!

Closing this in favor of #137, if that is okay with you.

This can be done as soon as upstream changes are integrated: https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1082
