### ISSUE TITLE
feat: renew fidelity bond

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#610]
> If "renew" is still a priority I'd say we create a new issue.

_Originally posted by @dergigi in https://github.com/joinmarket-webui/jam/issues/547#issuecomment-1422564749_

Feature: Provide an easy way for users to renew expired fidelity bonds. e.g. if a user wants to explicitly use the same UTXO for a new fidelity bond without an intermediary "unlock" operation.

**Describe the solution you'd like**
A concrete way to renew an expired FB without unfreezing it manually via the UI.
Prevent FBs from being unfrozen after they expire, but let it be used via distinct actions, -> See screenshots.

**Describe alternatives you've considered**
All alternatives that come to mind involve several manual steps by a user, which feels unnecessarily complicated.

**Additional context**
<img src="https://user-images.githubusercontent.com/3358649/196885718-5be11740-02f6-4496-90f0-aed006438032.png" width=400 />

**Comment by Seccour** [comment]
The fees should be displayed when creating or renewing a Fidelity Bond just so users don't end up creating FBs and realize afterwards that it wasn't worth it

**Comment by theborakompanioni** [comment]
> The fees should be displayed when creating or renewing a Fidelity Bond just so users don't end up creating FBs and realize afterwards that it wasn't worth it

I thought about tackling this next. Thanks for your input :orange_heart: Will be considered!
