### ISSUE TITLE
Paid more mining fee than the software prompted me

### ISSUE THREAD

**Issue by AngeloMetal** [joinmarket-webui/jam#613]
**Expected behavior**
I deposited 1,041,451 sats to Jam's receiving address (which is the jm wallet). 

I have set absolute limit (per collaborator) to 1000. I have set relative limit (per collaborator) to 0.001 (%). In mining fees, I have chosen 3 sat/vb with 20% fee randomization. I had also selected 9 collaborators. 

Before I mixed, I'd expect to pay less than 9*1000, plus some extra in mining fees. 

**Actual behavior**

Instead, I paid 31,365 sats in total. 

**Steps to reproduce the problem**
  1. Install Jam
  2. Adjust the fee limits
  3. Deposit money and use "Send" to mix them

**Specifications**
  - Version: v0.1.4
  - Platform: I installed it using Raspibolt's guide. I run a RPi with Raspibolt. I'm not sure what else I should write here. 
  - Browser: Firefox, probably one of latest versions.

**Additional context**

I don't know if it's JoinMarket's fault or yours, but since your software is in beta, I will bring the issue here first.

Can someone explain me why I paid more than expected?

Edit: I know I have made my coinjoin pointless, but I really want to know so I can avoid later on.

**Comment by theborakompanioni** [comment]
Hey @AngeloMetal, thanks for the report. 

> Can someone explain me why I paid more than expected?

Stating the fees of a transaction beforehand is quite tricky, but 31k seems an awful lot. To find the underlying issue, would you please verify the exact amount of mining fees and the fee rate of your transaction? Please know that the fee settings do not persist and have to be adapted after the service is restarted. I guess you did not restart the service or locked/unlocked the wallet before initiating the transaction, right?

>  I'd expect to pay less than 9*1000, plus some extra in mining fees.

Your expectation is correct. However, there is no way of knowing how many inputs/outputs another maker is adding to the transaction beforehand. Still `31k - 9k := 22k` feels too high given your mentioned fee settings.

**Comment by AngeloMetal** [comment]
Hello @theborakompanioni 
> To find the underlying issue, would you please verify the exact amount of mining fees and the fee rate of your transaction? 

Yes, here's the transaction itself: ``c9a1a4b8695a84bc7b4f601ddbe8a54292abcea876d2a16305c8d4216ad24a15``
As you can see, for some reason, I paid 30,983 sats just for the transaction fee. As far as I understand, this means that the taker (unless they're the miner :p ) only earned 382 sats. 

I confirm that in my non-restarted Jam I still have base fee = 3, and fee randomization = 20.

> Your expectation is correct. However, there is no way of knowing how many inputs/outputs another maker is adding to the transaction beforehand.

Wait. So you're telling me that if someone puts there stupidly many inputs I will pay their for all their block space?

**Comment by MaxHillebrand** [comment]
> Wait. So you're telling me that if someone puts there stupidly many inputs I will pay for all their block space?

I think yes, but the default joinmarket maker script does not add unnecessary outputs, just two.

**Comment by AngeloMetal** [comment]
Still not it's not the problem. The problem is that Jam somehow told JoinMarket to charge 24.2 sat/vb without my consent.

**Comment by theborakompanioni** [comment]
> > I confirm that in my non-restarted Jam I still have base fee = 3, and fee randomization = 20.
> 
> I'm not sure how it works in JAM (I _think_ you have to select between sat/vb and block target with block target being the default), but in JoinMarket that would select a feerate expected to confirm in 3 blocks. While 3000 would be 3 sat/vb. If you, maybe by accident, selected 3 blocks target instead of 3 sat/vb, then that could definitely explain your situation.

Hmm.. that might indeed be the cause.. @AngeloMetal can you verify you are using a sats/vbyte limit instead of a block target (which will use the estimate from bitcoin core)? Also, if you manually adapted your config file, it is like @PulpCattel said, `3` means "block target", `3_000` means "3 sats/vybte". See https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/v0.9.9/jmclient/jmclient/configure.py#L271-L280
That would explain the amount of fees in the current environment.

However, _if_ that really is the culprit, then maybe there is a way for Jam to explain it better or make it more clear to the user. There is a confirmation modal before a transaction is broadcasted, but maybe that can be improved. Suggestions are always highly appreciated. 

> The transaction was a sweep (which in JoinMarket terminology means it created no change for you), and sweeps have in general an estimation fee problem. You can read more [here](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/784#issuecomment-761057922) and in linked issues/PRs. Related to that, in JoinMarket config you can set a `max_sweep_fee_change` to prevent over/under paying.

Thanks for the link. Highly informative!

**Comment by AngeloMetal** [comment]
Indeed. The problem was that I had chosen block target instead of sats/vb. Thank you all.

**Comment by normanu** [comment]
I had chosen 55 sats/vB with a 10% deviation as a mining fee and in the end it was,

Fee	66,028 sat$28.38
Fee rate	105 sat/vB   Overpaid 2x

Im also confused how this came to be.
4 collaborators with a max fee of 0,01% 
Hope someone can explain it to me?

Log says,
Using this manually set tx feerate (randomized for privacy): 56242 sat/kvB (56.2 sat/vB).
fee breakdown for me totalin=xxxxxx my_txfee=66028
