### ISSUE TITLE
No connection to backend: Method Not Allowed.

### ISSUE THREAD

**Issue by nclgvnzz** [joinmarket-webui/jam#626]
**Expected behavior**

Be able to skip intro and create/view wallets.

**Actual behavior**

Getting error message "No connection to backend: Method Not Allowed." in the browser.

![Screen Shot 2023-06-23 at 21 53 09](https://github.com/joinmarket-webui/jam/assets/133590254/f29b0062-0505-4610-a417-3ba987bdaf09)

**Steps to reproduce the problem**
  1. Visit Jam URL
  2. Click on Skip Intro
  3. Error message is displayed

**Specifications**
  - Version: 0.1.5 on top of JoinMarket 0.9.9
  - Platform: Linux (Ubuntu Server 22.04) 
  - Browser: Google Chrome / Firefox

**Additional context**

I have recently rebuild my node due to hardware failure and I used to have Jam working with no major issue before that. The thing that changed with the new installation of Ubuntu Server 22.04 is that IPv6 is now enabled. I have already tried to [replace `localhost` with `127.0.0.1` in src/setupProxy.js](https://github.com/joinmarket-webui/jam/issues/608#issuecomment-1451831421) and [forwarding IPv6 requests on ports 28183, 28283 and 62601 to 127.0.0.1 (IPv4)](https://github.com/joinmarket-webui/jam/issues/608#issuecomment-1522515632) but no luck so far.

**Comment by 9808us** [comment]
First installation for me.
Following the guide on Raspibolt I had a first error about a Connection Timeout.
Then I replaced localhost with 127.0.0.1 and forwarded IPv6 like the OP did.
I then got the same result
![image](https://github.com/joinmarket-webui/jam/assets/38046064/de31ca94-c917-4d50-b0b1-1e9bdf840b09)

**Comment by 9808us** [comment]
This is console output

![image](https://github.com/joinmarket-webui/jam/assets/38046064/6950bf01-37f7-41a0-888e-f3df1d6df57f)

**Comment by nclgvnzz** [comment]
I tried disabling IPv6 altogether but still nothing.

**Comment by theborakompanioni** [comment]
This should hopefully be fixed with https://github.com/joinmarket-webui/jam/pull/611 which will be part of the next release. Apologies for the inconvenience. If you want you can try adapting the `src/setupProxy.js` yourself and test if this fixes your problem.

**Comment by 9808us** [comment]
JAM is connected (I think.. first time for me with Jam)infact the icon on botton right is green and telling Connected.

**Comment by 9808us** [comment]
From what I saw JAM starts and I'm presented with the welcome screen. But then whet JAM try to connect to a wallet it fails and stop with that message about 405

**Comment by 9808us** [comment]
Ok sorted and solved.

The issue is with this dep 'werkzeug'.

Please devs make sure to update jmclient/setup.py and use werkzeug = 2.2.0 

Looks like Ver 2.2.3 is broken for JAM and doesn't work



![image](https://github.com/joinmarket-webui/jam/assets/38046064/1c17bc54-c2ee-45a2-af15-9ef56e73e799)

![image](https://github.com/joinmarket-webui/jam/assets/38046064/b1a5010c-7d25-49e0-93be-d1d1b426e8b4)

**Comment by theborakompanioni** [comment]
> Ok sorted and solved @theborakompanioni

Great! Nice to hear that :rocket: 

> The issue is with this dep 'werkzeug'.
> 
> In JM make sure to update jmclient/setup.py and use werkzeug = 2.2.0

Okay...how could you possibly figure that out? Nice work.
I am not totally sure what is going on.. As far as I can see, v0.9.9 should still include v2.2.0.. The update to v2.2.3 (https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1486) is not released yet.. and will be just included in the next version. However.. I myself tested this on regtest with werkzeug v2.2.3 and it seemed to work fine.. Thanks for the heads up, fine sir :pray: I will take another look!

**Comment by nclgvnzz** [comment]
> Ok sorted and solved @theborakompanioni
> 
> The issue is with this dep 'werkzeug'.
> 
> In JM make sure to update jmclient/setup.py and use werkzeug = 2.2.0
> 
> Looks like Ver 2.2.3 is broken for JAM and doesn't work
> 
> JM 0.9.9 release is affected by this issue and doesn't work.
> 
> ![image](https://user-images.githubusercontent.com/38046064/249475102-1c17bc54-c2ee-45a2-af15-9ef56e73e799.png)
> 
> ![image](https://user-images.githubusercontent.com/38046064/249475912-b1a5010c-7d25-49e0-93be-d1d1b426e8b4.png)
> 
> ![image](https://user-images.githubusercontent.com/38046064/249479949-2c31f84b-606b-4633-9be8-978336f1071c.png)

@9808us @theborakompanioni could you please expand on this a little more? 

This is how `setup.py` in `jmclient` looks like on my machine:

```
from setuptools import setup


setup(name='joinmarketclient',
      version='0.9.9',
      description='Joinmarket client library for Bitcoin coinjoins',
      url='https://github.com/JoinMarket-Org/joinmarket-clientserver/tree/master/jmclient',
      author='',
      author_email='',
      license='GPL',
      packages=['jmclient'],
      install_requires=['joinmarketbase==0.9.9', 'mnemonic==0.20',
                        'argon2_cffi==21.3.0', 'bencoder.pyx==3.0.1',
                        'pyaes==1.6.1', 'klein==20.6.0', 'pyjwt==2.4.0',
                        'autobahn==20.12.3'],
      python_requires='>=3.6',
      zip_safe=False)
```
I don't see any "werkzeug" mentioned in there. Care to elaborate?

**Comment by nclgvnzz** [comment]
Am I supposed to manually add `'werkzeug==2.2.0'` after `'autobahn==20.12.3'`, then save and exit and run `./install.sh` once again to install that last dependency?

**Comment by nclgvnzz** [comment]
Ok so I went on and did exactly what I wrote in my previous comment and now the issue is solved. I can confirm that Jam is now working as expected, even with Werkzeug version 2.2.3 after reinstalling JoinMarket.

If anyone is facing the same issue, please try the following:

1) locate and open the `setup.py` file in your preferred text editor (this file should be in `joinmarket-clientserver-0.9.9/jmclient/`).

2) Check that `setup.py` contains `werkzeug==2.2.3` under `install_requires=`. If `werkzeug==2.2.3` is not there add it, save and exit so that `setup.py` looks more or less like this:

```
from setuptools import setup


setup(name='joinmarketclient',
      version='0.9.9',
      description='Joinmarket client library for Bitcoin coinjoins',
      url='https://github.com/JoinMarket-Org/joinmarket-clientserver/tree/master/jmclient',
      author='',
      author_email='',
      license='GPL',
      packages=['jmclient'],
      install_requires=['joinmarketbase==0.9.9', 'mnemonic==0.20',
                        'argon2_cffi==21.3.0', 'bencoder.pyx==3.0.1',
                        'pyaes==1.6.1', 'klein==20.6.0', 'pyjwt==2.4.0',
                        'autobahn==20.12.3', 'werkzeug==2.2.3'],
      python_requires='>=3.6',
      zip_safe=False)
```

3) Go back to the `joinmarket-clientserver-0.9.9` directory and run `./install.sh` once again. You will notice that at some point Werkzeug 2.2.3 will be installed.

![Screen Shot 2023-07-02 at 21 11 08](https://github.com/joinmarket-webui/jam/assets/133590254/b00d3546-0b6a-467a-83db-6aaf4f3f9ea9)

4) If you've followed the Raspibolt guide like me, restart the following system services: **jmwalletd.service**, **obwatcher.service** and **jam.service**. Wait few seconds and open Jam in your browser. You should now be able to skip the intro and use the app as expected.

![Screen Shot 2023-07-02 at 21 24 31](https://github.com/joinmarket-webui/jam/assets/133590254/ecdfb935-2034-46c1-9c3a-6662e8a0743e)

@9808us not sure why you had to use `'werkzeug==2.2.0'` instead of `'werkzeug==2.2.3'` but thanks a lot for mentioning that dependency as it was not even mentioned in my `setup.py`.

@theborakompanioni I am not sure if there's anything else to add here. In my case, JoinMarket's `setup.py` file didn't even have `werkzeug` listed under `install_requires=`. That was exactly what was preventing Jam from working as expected. I'll just close this issue for the time being.

**Comment by theborakompanioni** [comment]
> Ok so I went on and did exactly what I wrote in my previous comment and now the issue is solved. I can confirm that Jam is now working as expected, even with Werkzeug version 2.2.3 after reinstalling JoinMarket.

Glad you did make it work, but it seems strange, as you should not need to make manual changes obviously.
Have you checked out tag `0.9.9` or have you been on `master`? Have you made any other changes previously?

> @theborakompanioni I am not sure if there's anything else to add here. In my case, JoinMarket's `setup.py` file didn't even have `werkzeug` listed under `install_requires=`. That was exactly what was preventing Jam from working as expected. I'll just close this issue for the time being.

ping @kristapsk for the sake of clarity.

**Comment by kristapsk** [comment]
> > Glad you did make it work, but it seems strange, as you should not need to make manual changes obviously.
> > Have you checked out tag `0.9.9` or have you been on `master`? Have you made any other changes previously?
> 
> As per the [RaspiBolt](https://raspibolt.org/guide/bonus/bitcoin/joinmarket.html#installation) guide, I checked specifically for version `0.9.9`. I also tried to download the zip file from the releases page and I can confirm that the `setup.py` file doesn't have `werkzeug` listed under `install_requires=`.

Version pinning for `werkzeug` was added with https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1485, after v0.9.9 release.
