### ISSUE TITLE
RBF transaction counted twice

### ISSUE THREAD

**Issue by PLK2** [joinmarket-webui/jam#631]
**Expected behavior**

While receiving coins into a jar (e.g., 1m sats), transaction was RBF'd; expected to see only one UTXO for a single receive amount (of 1m sats).

**Actual behavior**

The original transaction and the subsequent RBF transaction show up as two separate UTXOs (e.g., of 1m sats each) and are counted twice (2m sats).

The RBF transaction has 6+ confirmations; the previous transaction still shows 0 confirmations.

I was unable to "sweep" the funds to another jar (I got an error saying `WARNING]  error pushing = -25 bad-txns-inputs-missingorspent...[ERROR]  Transaction broadcast failed!`) so I had to send "half" the funds, which went through. However, the original jar still shows the old UTXO with 0 confirmations as if it's expecting 1m sats.

**Steps to reproduce the problem**
  1. Send bitcoins to a jar.
  2. RBF that transaction.
  3. Once confirmed, the old transaction continues to display in the jar (with 0 confirmations) and persists.

**Specifications**
  - Version: 0.1.5
  - Platform: Start9 Start OS linux
  - Browser: Firefox

**Additional context**

**Comment by PLK2** [comment]
No problem--submitted!
https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1507

**Comment by theborakompanioni** [comment]
> No problem--submitted! [JoinMarket-Org/joinmarket-clientserver#1507](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1507)

Perfect :ok_hand: 
Closing the issue now and will follow the new one very closely!
Thank you!  :pray:
