### ISSUE TITLE
Created fidelity bond does not show up

### ISSUE THREAD

**Issue by realSaltyFish** [joinmarket-webui/jam#651]
**Expected behavior**

The "Earn" tab shows created fidelity bonds.

**Actual behavior**

My created fidelity bond does not show up in the "Earn" tab, neither in the orderbook.

**Steps to reproduce the problem**
This is what I experienced. I am also very lost on what actually happened and why. I am doing my best to describe the situation.

  1. I tried to create a fidelity bond with a specific UTXO, and somehow it failed. I didn't take note of the error message.
  2. I retried, and it failed again, presumably due to the same reason.
  3. I refreshed the page and wanted to try again, but I noticed that an UTXO I never selected had become frozen. However, it did not show up as a configured fidelity bond. When I use `wallet-tool` to view my wallet, the address is shown as "frozen" but no expiration date is given.

I selected September when I attempted to create the fidelity bond, so I can wait for a week to see if it unfreezes by 9/1, but I suspect there might be some unusual problems here because normally the expiration date would be at least shown in the wallet tool output. This bug caused me significant trouble because a very large proportion of my funds are now locked for an unknown period.

**Specifications**
  - Version: `jam-ui-only:v0.1.5-clientserver-v0.9.9`
  - Platform: Docker
  - Browser: Firefox 116

Please let me know what information you might need to pinpoint the issue. Also, could someone please guide me on making sure my funds are not locked indefinitely?

**Comment by theborakompanioni** [comment]
Hey @realSaltyFish,

from what you described it looks like no fidelity bond has been created (no transaction was broadcasted).
In order for Jam to use specific UTXOs for the bond, all UTXOs not participating in the bond are frozen and only unfrozen at the end of the flow. Meaning, UTXOs that were not selected in an aborted creation flow will stay frozen.

I'd say you can unfreeze them manually yourself and try creating a FB again. Why the flow did not succeed the first time, I cannot tell. If an error occurs if you try again, please take note of the error message. 

Hope this helps.

**Comment by realSaltyFish** [comment]
Hello @theborakompanioni,
Thanks for the info. It seems that the error caused some internal states corruption. I "unfroze" the funds by rescanning the joinmarket wallet in Bitcoin Core.

**Comment by theborakompanioni** [comment]
Hey @realSaltyFish, I kind of don't understand exactly what was wrong and would be happy do investigate further. But you closing the issue means, the problem is solved for you? I had the feeling I might have been wrong with my analysis and I just want to make sure you can access all your funds.

"Freezing" and "unfreezing" can also be done from the Jar Details View (if you click on any jar on the main screen).
If something is still unclear or if you have further questions, feel free to reopen this issue!
