### ISSUE TITLE
improve and thus speed up seed verification

### ISSUE THREAD

**Issue by editwentyone** [joinmarket-webui/jam#653]
make it possible that the cursor jumps to the next field automatically after correct verification, that should speed up the verification process 

<img width="690" alt="image" src="https://github.com/joinmarket-webui/jam/assets/96262473/46ca2abd-1143-4141-a40c-6b54ba2733a6">

**Comment by theborakompanioni** [comment]
Closed by #718. Many thanks to @zmjohnso!
