### ISSUE TITLE
feat: use new authentication mechanism (access/refresh token)

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#663]
Newest `master` of JM contains changes to the authentication mechanism.
See https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1480 for more information.

From [JSON-RPC-API-using-jmwalletd.md#rules-about-making-requests](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/JSON-RPC-API-using-jmwalletd.md#rules-about-making-requests):

> On initially creating, unlocking or recovering a wallet, a new access and refresh token will be sent in response, the former is valid for only 30 minutes and must be used for any authenticated call, the former is valid for 4 hours and can be used to request a new access token, ideally before access token expiration to avoid unauthorized response from authenticated endpoint and in any case, before refresh token expiration.

The OpenAPI spec can [be found in wallet-rpc.yaml](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/api/wallet-rpc.yaml).

At the time of writing, this functionality has not been released and will probably land in JM `v0.9.11`.

**Comment by theborakompanioni** [comment]
This has to be addressed as soon as possible in order for the development environment to work for everyone running `npm run regtest:rebuild` after commit https://github.com/JoinMarket-Org/joinmarket-clientserver/commit/6e6e68b1caa60401e8efd838a9253e8d3a16998f

If you are in this situation, you can rebuild the docker environment with a JM backend of tag `v0.9.10` instead of `master` (adapt `REPO_REF` in file `./docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile`) and execute `npm run regtest:rebuild` again.

**Comment by theborakompanioni** [comment]
> This has to be addressed as soon as possible in order for the development environment to work for everyone running `npm run regtest:rebuild` after commit [JoinMarket-Org/joinmarket-clientserver@6e6e68b](https://github.com/JoinMarket-Org/joinmarket-clientserver/commit/6e6e68b1caa60401e8efd838a9253e8d3a16998f)
> 
> If you are in this situation, you can rebuild the docker environment with a JM backend of tag `v0.9.10` instead of `master` (adapt `REPO_REF` in file `./docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile`) and execute `npm run regtest:rebuild` again.

Addressed by #664. Thanks @dergigi :pray:

**Comment by theborakompanioni** [comment]
So, this is generally ready for review. However, I am leaving it in "draft" mode as there is still an upstream problem with wallets that contain whitespaces, see https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1480#issuecomment-1729669816.

@roshii I'd highly appreciate if you could take a look. :pray:

**Comment by roshii** [comment]
> @roshii I'd highly appreciate if you could take a look. 🙏

I'm on it, ready by the end of the week latest.

**Comment by theborakompanioni** [comment]
> > @roshii I'd highly appreciate if you could take a look. 🙏
> 
> I'm on it, ready by the end of the week latest.

Nice. No time specifications required. Absolutely no urgency involved. 
Thanks, brother :orange_heart:
