### ISSUE TITLE
Missing max_cj_fee_abs and max_cj_fee_rel in configuration file could be handled better

### ISSUE THREAD

**Issue by jambolo** [joinmarket-webui/jam#673]
The variables `max_cj_fee_abs` and `max_cj_fee_rel` are disabled by default in joinmarket.cfg. If the variables are left disabled, then attempting to adjust fees in Jam gives this response:

> Error while loading fee config values.

I feel that the response is not helpful because it is too vague.

My suggestion is to specify which variables are missing, as well as stating that the are required to be given a value in joinmarket.cfg.
A second suggestion is to provide defaults when the variables are missing (if possible) rather than responding with an error message.

**Comment by theborakompanioni** [comment]
Hey @jambolo!

Thanks for the feedback. Very valid request.
Jam is reluctant to provide default values, so it opts to show a warning on the Send page, and also makes the fee config modal handle with missing values properly in #674.

Let me know if that is what you had in mind.

Thanks :pray:

**Comment by jambolo** [comment]
Your solution looks good to me.
