### ISSUE TITLE
016 Imported wallet starts rescan.  When I lock the wallet, it says it's "Inactive" which makes me think 

### ISSUE THREAD

**Issue by gStart9** [joinmarket-webui/jam#682]
... makes me think it's "lock wallet" stops a rescan:
![image](https://github.com/joinmarket-webui/jam/assets/106188942/1fc652a4-ba56-40a8-8502-c2bd9749f828)

**Is your feature request related to a problem? Please describe.**

Not really, just a display issue.  "Inactive" wallet makes me think its rescan stopped.

**Describe the solution you'd like**

"Inactive" status should be "locked", perhaps.  Or something to indicate it is still rescanning.

**Comment by theborakompanioni** [comment]
Replace labels "active"/"inactive" with something else ("locked" and "unlocked" seems more accurate) and/or show a rescanning indicator on this page too. What do you think @editwentyone ?

**Comment by editwentyone** [comment]
approved
