### ISSUE TITLE
Balance Component - Spacing, Coloring and Grouping

### ISSUE THREAD

**Issue by editwentyone** [joinmarket-webui/jam#690]
it would be nice to display all the balances grouped, colored and spaced "correctly" - like the bitcoin design community is suggesting it:
![Bildschirmfoto 2023-10-31 um 09 46 03](https://github.com/joinmarket-webui/jam/assets/96262473/b8daa09e-8e63-43eb-b50c-cbd538730d79)

- grouped by 0,00 000 000
- all the pre 0 coloured differently, like some alpha percentage
- spacing is a thing space https://www.compart.com/en/unicode/U+2009
- use also slashed Zeros if possible everywhere, where the user finds basically number-informations only (like table cells)
- use a monospace variant in tables or basically everywhere

this helps to see the sats :D see reference: https://bitcoin.design/guide/designing-products/units-and-symbols/#formatting-units

**Comment by editwentyone** [comment]
![Bildschirmfoto 2023-11-03 um 15 51 43](https://github.com/joinmarket-webui/jam/assets/96262473/990528f0-ff8b-47e9-b5ab-4da584ecfcf8)

more examples

**Comment by theborakompanioni** [comment]
@editwentyone Do you think the sats <-> BTC switch still makes sense after this change is applied, or should it be removed?

**Comment by theborakompanioni** [comment]
>     * spacing is a thing space https://www.compart.com/en/unicode/U+2009

Currently using ["Narrow No-Break Space (NNBSP)"](https://www.compart.com/en/unicode/U+202F) - okay?

**Comment by editwentyone** [comment]
> @editwentyone Do you think the sats <-> BTC switch still makes sense after this change is applied, or should it be removed?

just had the same thought and posted it under the solution (sorry): doesn't make any sense anymore!

**Comment by editwentyone** [comment]
> > ```
> > * spacing is a thing space https://www.compart.com/en/unicode/U+2009
> > ```
> 
> Currently using ["Narrow No-Break Space (NNBSP)"](https://www.compart.com/en/unicode/U+202F) - okay?

is https://www.compart.com/en/unicode/U+2009 think space same size? but its ok from what I saw.

> Also.. what should "all zero" (`0.00 000 000`) look like? All greyed out?

yes grayed out and also grey out the ₿ in front to the same grey level :) thanks

**Comment by theborakompanioni** [comment]
> > > ```
> > > * spacing is a thing space https://www.compart.com/en/unicode/U+2009
> > > ```
> > 
> > 
> > Currently using ["Narrow No-Break Space (NNBSP)"](https://www.compart.com/en/unicode/U+202F) - okay?
> 
> is https://www.compart.com/en/unicode/U+2009 think space same size? but its ok from what I saw.

Yes, I seems they are the same size - at least in the font Jam is using. I have changed it from `U+202F` to `U+2009` as you suggested.
> 
> > Also.. what should "all zero" (`0.00 000 000`) look like? All greyed out?
> 
> yes grayed out and also grey out the ₿ in front to the same grey level :) thanks

From a personal viewpoint.. I think it looks better if it is not greyed out..
![image](https://github.com/joinmarket-webui/jam/assets/3358649/264c09ce-0730-46e4-97ab-f9d94ee9ce87) ![image](https://github.com/joinmarket-webui/jam/assets/3358649/f299fb45-1186-4321-b09e-37183ee8a051)

What do you think?

**Comment by editwentyone** [comment]
> From a personal viewpoint.. I think it looks better if it is not greyed out.. ![image](https://user-images.githubusercontent.com/3358649/280644938-264c09ce-0730-46e4-97ab-f9d94ee9ce87.png) ![image](https://user-images.githubusercontent.com/3358649/280644843-f299fb45-1186-4321-b09e-37183ee8a051.png)
> 
> What do you think?

I think that when you have all 5 jars side by side, the white ₿ with grey zeros is somehow disruptive 


> Also, I like how the dot (`.`) is greyed out, on round amounts (e.g. `1.00 000 000`), but not when there are fractional amounts (e.g. `1.00 000 001`). This is also not specified from your examples, but I like it a lot.

that's fine, keep it that way

**Comment by theborakompanioni** [comment]
> > From a personal viewpoint.. I think it looks better if it is not greyed out..
> > What do you think?
> 
> I think that when you have all 5 jars side by side, the white ₿ with grey zeros is somehow disruptive. everything else is grey, like name and amount / zeros, but not the ₿. if its all grey when empty, then the users eye is instantly jumping to the jar with content

Agreed. Will be adapted!

> 
> > Also, I like how the dot (`.`) is greyed out, on round amounts (e.g. `1.00 000 000`), but not when there are fractional amounts (e.g. `1.00 000 001`). This is also not specified from your examples, but I like it a lot.
> 
> that's fine, keep it that way

:+1:

**Comment by editwentyone** [comment]
@theborakompanioni I modified the colors and removed the alpha stuff

<img width="1784" alt="image" src="https://github.com/joinmarket-webui/jam/assets/96262473/8e737d22-b672-450c-b426-0d4a59248000">


https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?type=design&node-id=2850-67638&mode=design&t=8Lww14g967eGNGWC-11
