### ISSUE TITLE
Align all Amount Input Fields to ₿

### ISSUE THREAD

**Issue by editwentyone** [joinmarket-webui/jam#692]
it would be awesome to consolidate all input fields where the user needs to input an amount of sats / btc to the same component and styling:

- Receive » options
- Send
- Earn » options

Either B (icon) and Sats (kebab icon) switcher, or everything to B only. maybe even with a proper Placeholder Text with the same styling "0.00 000 000" but **when the user copy/paste values its of course **without** the spacing**

(added to 0.2.0, you can raise your hand and have a veto if you want to postpone that ;) ) 

Screenshots:
![Bildschirmfoto 2023-11-04 um 19 16 39](https://github.com/joinmarket-webui/jam/assets/96262473/32ea9d4d-23fa-46fd-affb-84d9f27442a2)
![Bildschirmfoto 2023-11-04 um 19 16 32](https://github.com/joinmarket-webui/jam/assets/96262473/791ba22b-6bd1-4cd6-ac76-43e4c04d0f46)
![Bildschirmfoto 2023-11-04 um 19 16 21](https://github.com/joinmarket-webui/jam/assets/96262473/1c19e02d-c326-47f9-9f95-3f71538dc998)

**Comment by theborakompanioni** [comment]
> (added to 0.2.0, you can raise your hand and have a veto if you want to postpone that ;) )

It's okay! However, please do not auto-assign me. You are destroying all my hopes that other fellow devs will ever contribute to the project :wink: 
Tagging it with "good-first-issue" would be nice (if the ticket is actually small and concise).

**Comment by editwentyone** [comment]
you still have hopes and dreams :)
