### ISSUE TITLE
feat: custom tx fee on direct-send

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#696]
Since https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1597 it is possible to specify the txfee directly on direct-send operations. 

Note: This feature must be hidden behind a version flag as it will only be available with backend version >= 0.9.11.

As a user, I want to specify a custom tx fee when creating a single transaction, so I not have to edit the config values on a per transaction basis. This can be done by adding a custom tx input field, prefilled with the config value, to the send options on non-collaborative sends.

Later, this functionality can be used when creating/unlocking/renewing fidelity bonds (https://github.com/joinmarket-webui/jam/pull/678).

**Comment by kristapsk** [comment]
From Jam UX perspective, if custom fee can be specified for direct-send, wouldn't you like to have it also for `/wallet/{walletname}/taker/coinjoin`? Implementation should not be hard, `scripts/sendpayment.py` already support it for both coinjoin and non-coinjoin sends.

**Comment by theborakompanioni** [comment]
> From Jam UX perspective, if custom fee can be specified for direct-send, wouldn't you like to have it also for `/wallet/{walletname}/taker/coinjoin`? Implementation should not be hard, `scripts/sendpayment.py` already support it for both coinjoin and non-coinjoin sends.

That would indeed be awesome. :rocket: 
Thanks @kristapsk
