### ISSUE TITLE
Include Info about Dev setup feature in contributing.md and and within app

### ISSUE THREAD

**Issue by Dayvvo** [joinmarket-webui/jam#724]
In order to provide a smoother experience in Dev mode I would suggest the following:

- Include a summary on the dev setup features such as the RPC terminal and block explorer as well as instructions on how to access them using the dev setup page in the [Contributing](https://github.com/joinmarket-webui/jam/blob/master/CONTRIBUTING.md) file. This would provide more clarity on navigating the app and executing actions that require the Jam RPC terminal or the Jam block explorer in dev mode.

- Include hints about the dev setup at certain points within the app. e.g. After using the "Send" feature to make a transfer. The app warns that "a collaborative transaction requires a 5-block confirmation before that UTXO is usable again". Including a hint in that warning message that blocks can be mined to your address in dev mode using the Jam RPC i.e `generatetoaddress 5 "Your address"` to confirm the transaction

![Screenshot (885)](https://github.com/joinmarket-webui/jam/assets/45407706/45cf7f36-8eff-4482-bd09-b680a351f0d1)

**Comment by theborakompanioni** [comment]
Hey @Dayvvo.

Good ideas. There are certain pages where some info is present when running in dev mode, so this should be fine :+1: 
Thanks so much for the suggestions.
