### ISSUE TITLE
Dev-setup route does not have multi-language support

### ISSUE THREAD

**Issue by Dayvvo** [joinmarket-webui/jam#732]
The Dev Setup page at /dev-setup has it's text hardcoded in English. When I set the default language to another language, the dev-setup route remains in English. It would be nice for it to have multi-language support like the other pages in the app

**Comment by theborakompanioni** [comment]
Hey @Dayvvo!
Thanks for the suggestion. The page is not translated on purpose as it is only displayed in dev mode and not in the production build. From my point of view, this is completely fine, as all devs are encouraged to use English as the main language while developing e.g. write documentation, comments, etc.. There is hardly any benefit, but puts a burden on translators, so I'd say, this is not something we should do. Does that make sense to you? :pray:

**Comment by Dayvvo** [comment]
Now that you mention it I agree. I'll go ahead and close the issue then
