### ISSUE TITLE
Umbrel Home: Keine Verbindung zum Backend: The server reported a problem: 502 Bad Gateway.

### ISSUE THREAD

**Issue by fsm247** [joinmarket-webui/jam#733]
**Expected behavior**

JAM up and running

**Actual behavior**

After installing the JAM App on a brand new umbrel home server, I am getting the message:

No Connection
Keine Verbindung zum Backend: The server reported a problem: 502 Bad Gateway.

**Steps to reproduce the problem**
  1. Tried reinstalling JAM
  2. Tried installing Electrs before installing JAM
  3. Only apps running on my Umbrel Home right now are Bitcoin Node (finished syncing), Electrs and Jam.

**Specifications**
  - Version: Jam v0.2.0
  - Platform: Umbrel Home
  - Browser: Google Chrome Version 123.0.6312.86

**Additional context**

Pretty self explanatory error message.
Any ideas how to fix this? The Umbrel Home server is brand new and was just set up yesterday.

**Comment by MarnixCroes** [comment]
hi @fsm247 

is it your first time trying Jam?

Did you try adding `deprecatedrpc=create_bdb` to your bitcoin.conf file?
see https://jamdocs.org/FAQ/#jam-doesnt-work-anymore-after-updating-bitcoin-core-to-v260

FYI, someone on telegram had the same problem with the new Umbrel 1.0, adding it to the config didn't work AFAIK. then I'm not sure how to fix it sorry

**Comment by theborakompanioni** [comment]
Link to issue on the umbrel repo: https://github.com/getumbrel/umbrel/issues/1736

Let's hope this will be resolved soon.

**Comment by fsm247** [comment]
> hi @fsm247
> 
> is it your first time trying Jam?
> 
> Did you try adding `deprecatedrpc=create_bdb` to your bitcoin.conf file? see https://jamdocs.org/FAQ/#jam-doesnt-work-anymore-after-updating-bitcoin-core-to-v260
> 
> FYI, someone on telegram had the same problem with the new Umbrel 1.0, adding it to the config didn't work AFAIK. then I'm not sure how to fix it sorry

Unfortunately this hasn't fixed my problem.
Hopefully there will be a fix soon.
Jam was one of the main reasons why I got the Umbrel Home in the first place.

**Comment by theborakompanioni** [comment]
> > hi @fsm247
> > is it your first time trying Jam?
> > Did you try adding `deprecatedrpc=create_bdb` to your bitcoin.conf file? see https://jamdocs.org/FAQ/#jam-doesnt-work-anymore-after-updating-bitcoin-core-to-v260
> > FYI, someone on telegram had the same problem with the new Umbrel 1.0, adding it to the config didn't work AFAIK. then I'm not sure how to fix it sorry
> 
> Unfortunately this hasn't fixed my problem. Hopefully there will be a fix soon. Jam was one of the main reasons why I got the Umbrel Home in the first place.

Just to be sure.. did you restart your node after the config change?

**Comment by fsm247** [comment]
> > > hi @fsm247
> > > is it your first time trying Jam?
> > > Did you try adding `deprecatedrpc=create_bdb` to your bitcoin.conf file? see https://jamdocs.org/FAQ/#jam-doesnt-work-anymore-after-updating-bitcoin-core-to-v260
> > > FYI, someone on telegram had the same problem with the new Umbrel 1.0, adding it to the config didn't work AFAIK. then I'm not sure how to fix it sorry
> > 
> > 
> > Unfortunately this hasn't fixed my problem. Hopefully there will be a fix soon. Jam was one of the main reasons why I got the Umbrel Home in the first place.
> 
> Just to be sure.. did you restart your node after the config change?

Yes I did.

**Comment by theborakompanioni** [comment]
> > Just to be sure.. did you restart your node after the config change?
> 
> Yes I did.

Can you double-check that the config changes are still present? Node is synced? Please forgive the annoying follow-up questions..

**Comment by fsm247** [comment]
> > > Just to be sure.. did you restart your node after the config change?
> > 
> > 
> > Yes I did.
> 
> Can you double-check that the config changes are still present? Node is synced? Please forgive the annoying follow-up questions..

Will do after dinner. Give me a few hours.
I appreciate the follow-up.

**Comment by fsm247** [comment]
> > > Just to be sure.. did you restart your node after the config change?
> > 
> > 
> > Yes I did.
> 
> Can you double-check that the config changes are still present? Node is synced? Please forgive the annoying follow-up questions..

Ok I removed the deprecatedrpc=create_bdb line from bitcoin.conf
Restarted.
Added the line back in. Saved. Restarted.
Now Jam seems to be working.
No idea what I did wrong in the first attempt.
Thanks anyway :-)

**Comment by theborakompanioni** [comment]
> Now Jam seems to be working.

Nice! That's great :pray:
