### ISSUE TITLE
Metamask wallet 

### ISSUE THREAD

**Issue by A1985J09** [joinmarket-webui/jam#736]
**Expected behavior**

**Actual behavior**

A clear and concise description of what the bug is and what actually happens.

**Steps to reproduce the problem**
  1.
  2.
  3.

**Specifications**
  - Version:
  - Platform:
  - Browser:

**Additional context**

Add any other context about the problem here to help explain your problem.
e.g. error logs or screenshots if applicable. Make sure to remove any confidential information before sharing screenshots or logs.

**Comment by theborakompanioni** [comment]
Closing. No description.
