### ISSUE TITLE
0 conf when maker, # conf when taker

### ISSUE THREAD

**Issue by editwentyone** [joinmarket-webui/jam#746]
when looking inside the jars, I can see UTXOs with normal conf counting up, when I was the taker. 
looking at UTXOs where I was the maker and so part of a CJ, the conf stays at 0 visually, even when I can double check the TX ID with mempool.space

**Steps to reproduce the problem**
  1. be part of a CJ as a maker

**Specifications**
  - Version: 0.2.0

**Comment by theborakompanioni** [comment]
Hey @editwentyone, thanks for your report!

This is data coming from the backend API - Jam is just a UI and will display whatever JM delivers.
Might be already reported on the backend: https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1588

Can you elaborate your case there a bit? Guess it helps JM devs greatly!
I am not able to reproduce this on regtest, it seems.

If it is okay for you, I will close this issue shortly.

**Comment by editwentyone** [comment]
will do, thanks, closing myself :)
