### ISSUE TITLE
fix: remove twitter link

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#750]
Twitter links are broken - replace with link to nostr or remove entirely.

**Comment by KellyKiiru** [comment]
Hello. Kindly assign this issue to me.

**Comment by 0xSaksham** [comment]
@theborakompanioni I think this issue is completed. Shouldn't this be closed?

**Comment by 0xSaksham** [comment]
![image](https://github.com/joinmarket-webui/jam/assets/90046016/bc20f31d-6e05-462f-b651-590986d92139)

There is this one in the settings panel. Should I make a PR to remove this also?
