### ISSUE TITLE
Modal instead of dropdown for new fidelity Bond creation form

### ISSUE THREAD

**Issue by barrytra** [joinmarket-webui/jam#760]
**Is your feature request related to a problem? Please describe.**
Currently to create a new fidelity bond, we have a dropdown which extends down the page. which is kind of disturbing for user.
![Screenshot from 2024-05-21 12-48-06](https://github.com/joinmarket-webui/jam/assets/109822630/fb2d9029-4e6c-4550-97f5-77b47f87143d)
![Screenshot from 2024-05-21 12-48-25](https://github.com/joinmarket-webui/jam/assets/109822630/61798a03-718a-48d3-8fbc-0493c3daf389)

**Describe the solution you'd like**
Its better to have a separate area like a modal to create a new bond. So instead of a dropdown on the same page, we would have a popup there itself when user clicks "Configure Fidelity Bond".

**Comment by theborakompanioni** [comment]
Perfect! Concept ACK :ok_hand:
