### ISSUE TITLE
ui: Improve readablity of balances in light mode on dark backgrounds

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#770]
Balances do not look very nice in light mode on dark backgrounds, e.g. in tooltips.
They should be made more readable and easy on the eyes.

![Screenshot from 2024-05-28 23-09-32](https://github.com/joinmarket-webui/jam/assets/109822630/405a2891-3492-4e08-a625-89d30cc14814)

_Originally posted by @barrytra in https://github.com/joinmarket-webui/jam/issues/766#issuecomment-2135791517_

**Comment by SnehalSrivastava27** [comment]
@theborakompanioni is this issue still open ?

**Comment by SnehalSrivastava27** [comment]
@barrytra Can I take up this issue

**Comment by barrytra** [comment]
Lets discuss it here @SnehalSrivastava27 
Can u show me what error do u get on running `npm run regtest:rebuild` and `npm run regtest:up`

**Comment by SnehalSrivastava27** [comment]
This is what I get on npm run regtest:rebuild
![image](https://github.com/joinmarket-webui/jam/assets/118104081/ad6c66e0-d4e5-4b86-91bb-b40e6b06265c)

and This is what I get on npm run regtest:up
![image](https://github.com/joinmarket-webui/jam/assets/118104081/399d9039-3864-4b9d-ae93-d7acd0d5f63a)

**Comment by SnehalSrivastava27** [comment]
I am almost ready with solving the issue but facing problem in running backend

**Comment by SnehalSrivastava27** [comment]
@barrytra yes

**Comment by kristapsk** [comment]
> Regarding the second error: Since it seems you are using some version of Windows, I am afraid I cannot reproduce the issue. I would have thought there is some kind of posix subsystem to make it work ("Windows Services for Linux", WSL?) or something.. (but I am not familiar with it and hence unable to help).

[WSL2](https://learn.microsoft.com/en-us/windows/wsl/install) is the way to go for Windows nowadays. It allows to run Ubuntu or whatever Linux distro you want under Windows 10/11.

P.S. "Windows Subsystem for Linux" (not "Services"). :)

**Comment by SnehalSrivastava27** [comment]
@theborakompanioni in the first issue I have run the command several times

**Comment by SnehalSrivastava27** [comment]
Hi everyone 
I am unable to locally setup the project tried more than 15 times therefore I apologize that I cannot contribute into this issue looking forward to contribute in future when I may face good device

**Comment by theborakompanioni** [comment]
> Hi everyone I am unable to locally setup the project tried more than 15 times therefore I apologize that I cannot contribute into this issue looking forward to contribute in future when I may face good device

Hey @SnehalSrivastava27 that is very unfortunate. I apologize that it is not working for you and that it does not seem to work or still needs effort to run the dev setup on Microsoft Windows™ Operating System.

**Comment by 0xSaksham** [comment]
I'll take a look at this when I'll have time.

**Comment by 0xSaksham** [comment]
> Hi everyone I am unable to locally setup the project tried more than 15 times therefore I apologize that I cannot contribute into this issue looking forward to contribute in future when I may face good device

Try dual booting your system with Fedora.

**Comment by SnehalSrivastava27** [comment]
@0xSaksham I have dual booted with Ubuntu and now the project is working smoothly also I have got my one PR merged
