### ISSUE TITLE
unable to sign in from Umbrel generated Jam

### ISSUE THREAD

**Issue by Estrellas22** [joinmarket-webui/jam#778]
*jam_app_proxy_1  | yarn run v1.22.19
jam_app_proxy_1  | $ node ./bin/www
jam_app_proxy_1  | [HPM] Proxy created: /  -> http://jam_web_1:80
jam_app_proxy_1  | Waiting for jam_web_1:80 to open...
jam_app_proxy_1  | Jam is now ready...
jam_app_proxy_1  | Listening on port: 5002
jam_web_1        | [WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
jam_web_1        | Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
jam_web_1        | To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
jam_web_1        | Remove leftover wallet lockfiles before startup...
jam_web_1        | Waiting for bitcoind to accept RPC requests...
jam_web_1        | Successfully waited for bitcoind to accept RPC requests.
jam_web_1        | Creating wallet jam_default if missing...
jam_web_1        | Loading wallet jam_default...
jam_web_1        | [  OK  ] nginx
jam_web_1        | [  OK  ] tor
jam_web_1        | [  OK  ] ob-watcher
jam_web_1        | [  OK  ] jmwalletd
jam_web_1        | [  OK  ] boot*Expected behavior**

**Actual behavior**

A clear and concise description of what the bug is and what actually happens.

**Steps to reproduce the problem**
  1.
  2.
  3.

**Specifications**
  - Version:
  - Platform:
  - Browser:

**Additional context**

Add any other context about the problem here to help explain your problem.
e.g. error logs or screenshots if applicable. Make sure to remove any confidential information before sharing screenshots or logs.

**Comment by theborakompanioni** [comment]
Hey @Estrellas22!

Logs seem okay. What do you mean with "unable to sign in from Umbrel"?
Basic auth is enabled on Umbrel - do you mean the user/password dialog?

**Comment by Estrellas22** [comment]
Issue resolved, close incident

**Comment by theborakompanioni** [comment]
> Issue resolved, close incident

Glad to hear @Estrellas22!
Would you mind telling us, what resolved the issue?
Future readers might benefit massively :-)
Thanks :pray:

**Comment by Estrellas22** [comment]
All I did was open the logon box in a Tor browser and it accepted the login credentials. After that it also opened in a non-Tor browser.I'm not very tech savvy so I can't really explain the reason why?On Fri, Jun 7, 2024 at 3:11 AM Thebora Kompanioni ***@***.***> wrote:

Issue resolved, close incident

Glad to hear @Estrellas22!
Would you mind telling us, what resolved the issue?
Future readers might benefit massively :-)
Thanks 🙏
