### ISSUE TITLE
Improve UI for account balance in send page

### ISSUE THREAD

**Issue by ghost** [joinmarket-webui/jam#78]
See discussion in https://github.com/joinmarket-webui/joinmarket-webui/pull/76#discussion_r802755495.

The balance that's shown when selecting which account to send from, is currently hard coded to whatever is returned from the server. That means it is always shown in BTC and can't be changed to sats.

That's because the `<option>` element only allows text children so we can't use the `<Balance>` component.

Maybe there's a way to fix this though? 🤷‍♂️ 

<img width="688" alt="Screenshot 2022-02-09 at 16 29 22" src="https://user-images.githubusercontent.com/10026790/153233380-9c10cd62-5083-4348-b832-9b0983ebfd3e.png">

**Comment by theborakompanioni** [comment]
In addition, the balance as currently displayed might not be spendable (e.g. utxo is frozen). There is [an issue open on the server repo](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1167) regarding this, but as discussed in the comments, it seems fair to delegate the handling to the client.

What do you think is the best way to handle this? There is a "balance breakdown" on "sweep" - might it be useful to display it as well when a mixdepth containing frozen coins is selected? Or should it be done differently?

**Comment by editwentyone** [comment]
frozen coins are frozen for a reason right? for the normal user it should be easier to identify what amount can be moved without making bad decision and kill the privacy aspect. 

can we re-render the first dropdown when the user switches from B to S(ats) in the second form field? 

https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/?node-id=3420%3A75738

**Comment by MaxHillebrand** [comment]
> frozen coins are frozen for a reason right?

Not 100% certain, but I think coins are only frozen based on user explicitly doing it.

**Comment by theborakompanioni** [comment]
> Not 100% certain, but I think coins are only frozen based on user explicitly doing it.

Coins are definitely [automatically frozen on address reuse](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/8c57852b2ae3c5a6ca0ec39724495d391982cfc2/docs/release-notes/release-notes-0.6.2.md#auto-freeze-of-deposits-to-reused-addresses). But since nobody is doing that,.. I think you are right : D

**Comment by editwentyone** [comment]
also, because collaborative tx are default, it would be awesome to show the alternative (normal send, deactivated collaborative tx) more direct: 

red deactivated slider + rename the send button to another wording, please see

https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/?node-id=3427%3A75184

**Comment by dnlggr** [comment]
> so is there a simple way to access the highest possible amount a user can spend?

Yes but also no. See discussion [here](https://github.com/joinmarket-webui/joinmarket-webui/pull/184#issuecomment-1072380854). We can do a (really) good estimate though.

**Comment by dnlggr** [comment]
Parts of this (the BTCC/sats conversion) will be resolved in #276. The "spendable balance" issue remains mostly a UI issue since we'll get the spendable and total balance by the server [soon](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1285).

**Comment by editwentyone** [comment]
🎨 https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=2850%3A70953&viewport=-1615%2C-4716%2C0.84

<img width="730" alt="image" src="https://user-images.githubusercontent.com/96262473/196470892-3a78208d-bf25-4942-b775-95a6ce327b01.png">

**Comment by editwentyone** [comment]
bump :P

**Comment by theborakompanioni** [comment]
> bump :P

This is already on my priority list - need to wait for https://github.com/joinmarket-webui/jam/pull/587 and https://github.com/joinmarket-webui/jam/pull/595 to be merged. Care to review? : D

**Comment by editwentyone** [comment]
get me on a call with you and go through the review with me once, lets see if I can be of any help.

**Comment by theborakompanioni** [comment]
Resolved with #600.
