### ISSUE TITLE
dev: default for collaborators based on active maker count

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#780]
As a developer new to the project, it is not obvious that one needs to adapt the default collaborator count (randomized between `8` - `10`) to `1` or `2` (as this is the active makers that are started when running `npm run regtest:init`). Otherwise the collaborative transaction will always fail.

It should be more obvious to know what to do, e.g. either by setting the default to be `1` or `2`, or by providing another visual hint in the UI when the app is started in dev mode (`npm run dev:start`).

**Comment by editwentyone** [comment]
default just to 1, 2 or input field as selectable options and add an orange "dev" tag at the title above ?!
