### ISSUE TITLE
(ui) Circular Progress Bar around Cooking Pot Visual

### ISSUE THREAD

**Issue by 0xSaksham** [joinmarket-webui/jam#792]
Subtask of #319 
Aim: To make the Progress Bar Rounded around the cooking pot.

![image](https://github.com/joinmarket-webui/jam/assets/90046016/70575f08-ac6f-4219-b098-cb2458e72fbe)

Objective: To change the CSS variables in the module.css files and making the change happen.

**Comment by 0xSaksham** [comment]
This is taking more time. I'll keep trying but not as a main task and focus on other tasks.

**Comment by 0xSaksham** [comment]
@theborakompanioni , I would need #804  to be merged to start work on this task.

**Comment by theborakompanioni** [comment]
Closing this in favor of parent task #319.
