### ISSUE TITLE
no option to Copy seed phrase

### ISSUE THREAD

**Issue by nischal-shetty2** [joinmarket-webui/jam#823]
Currently, we cannot copy the seed phrase to our clipboard for user convenience.

I'm not aware if this feature is intentionally omitted for security reasons.

Current implementation:

https://github.com/user-attachments/assets/ad0234e2-4d95-4d6f-9cd7-c60c3a7695b2

Proposed solution:

https://github.com/user-attachments/assets/5cdbb418-5455-4452-8bc1-cff9dd458e93

I can create a PR if this feature is needed.

To view the current implementation, go to:
 ` /settings ` -> ` Show seed phrase `

**Comment by nischal-shetty2** [comment]
@theborakompanioni, is this intentionally not added (which I don't think is the case because wallets allow users to copy seed phrases, and it's the user's choice where to store it), or should I create a PR for this?

**Comment by theborakompanioni** [comment]
Hey @nischal-shetty2, you are right - albeit being a hot wallet and fetching the seed via API requests, which is a risk in and of itself - this has not been added as potentially damaging behaviour should not be encouraged. NACK from my side, but let's see what others have to say. @ping @editwentyone @amitx13 @barrytra 

Thanks for your contributions! There is so many other things that need love in case you are motivated to fix stuff. ~60 open issues at the time of writing.. :pray:

**Comment by nostitos** [comment]
COPY button is bad because it reduce the odds of someone saving it to a different medium (paper).

**Comment by nischal-shetty2** [comment]
> There is so many other things that need love in case you are motivated to fix stuff.

Definitely will try my best!

**Comment by editwentyone** [comment]
thank you for the proposal but as others stated, we are also dealing with people who have a hard time reading and an easy time losing their funds. so lets not make it way easier ;) 

looking forward to work with you
