### ISSUE TITLE
feat(rescan): enable rescanning chain

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#833]
Rescanning the chain has been an experimental feature and is hidden by default.

Making it available would help non-technical users to not going through the steps outlined in https://github.com/joinmarket-webui/jamdocs/issues/47 and does away the need to use the CLI.

<img alt="" width="350" src="https://private-user-images.githubusercontent.com/3358649/364312532-295bf6af-c90b-4a09-b0db-6eb7162d68f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDIwNzksIm5iZiI6MTcyNTQ0MTc3OSwicGF0aCI6Ii8zMzU4NjQ5LzM2NDMxMjUzMi0yOTViZjZhZi1jOTBiLTRhMDktYjBkYi02ZWI3MTYyZDY4ZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDkyMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg3MDIwYzE3Yzk2MGM0M2YyNTU3YWE2NWQ5MjNjMTAzOGViZGFhODBhYmM4MzYyNWU4Y2QxMjY3MmJlOWViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X9u5LYO0-7PsKu1Wdr93jcPg5RsWeB5qhlOz5em5jZ0">

Steps to do:
- i18n support: translate strings in the page component
- remove the dev badge
- Keep "experimental" in the title?

**Comment by nischal-shetty2** [comment]
ill create a pr for this feature but

> * Keep "experimental" in the title?

Should i keep this in? @theborakompanioni  @editwentyone

**Comment by theborakompanioni** [comment]
> ill create a pr for this feature but
> 
> > * Keep "experimental" in the title?
> 
> Should i keep this in? @theborakompanioni @editwentyone

Yes, I think we should keep it for now. It can always be removed later.
