### ISSUE TITLE
Add message to Jar Details View if operations are disabled

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jam#856]
When a maker or taker operation is running, the freeze/unfreeze buttons do not appear in the Jar Details View.
Currently, a user might be confused that the buttons are not displayed.
Add a message that explains why freezing/unfreezing is currently not possible.

**Comment by nischal-shetty2** [comment]
hey @theborakompanioni would love to work on this, what should the message be and how/where should it be displayed? @editwentyone

**Comment by theborakompanioni** [comment]
Hey @nischal-shetty2! Great to her! :pray: 

I think displaying a text that just says "A maker/taker operation is in progress. Some operations are disabled." is okay.  It can be shown right where the buttons would have been. What do you think? Optionally add an info icon that the user can click/hover to get more information. 

Also, what about still displaying the buttons but disable them? They do not really look pretty at the moment.. a visual update is highly welcome.

**Comment by theborakompanioni** [comment]
> What do you think about displaying `A maker/taker operation is in progress. Some operations are disabled.` right next to the info icon by default? This way, users get the context without needing extra effort.

Perfect :ok_hand:
