### ISSUE TITLE
Money didn't make it to destination wallet

### ISSUE THREAD

**Issue by gimmanyq** [joinmarket-webui/jam#857]
**Expected behavior**

When conducting a collab send, after the send was finished I checked my destination wallet and my balance was 0. I also went back to Jam to check my jar and the balance there was 0 as well. This has never happened but when I checked the address in cointracker I saw that the balance was still in the wallet, I just cannot see it in the UI. 

**Actual behavior**

A clear and concise description of what the bug is and what actually happens.

**Steps to reproduce the problem**
  1. Enter recipient wallet
  2. the amount (sweep)
  3. Sending options- the only thing that was changed was the mining fee --> sats/vByte and I set it to whatever number was appropriate at the time.

**Comment by theborakompanioni** [comment]
Hey @gimmanyq! Thanks for the report. First of all, funds should never disappear - quite bad UX, sorry for that. Funds are definitely not lost. Have you tried locking/unlocking the wallet? If that does not help, restart your node. If all those things fail, try rescanning the timechain starting blocks before the transaction and repeat the steps (locking/unlocking, restarting). Please report here if funds are displayed correctly after that. :pray:

**Comment by gimmanyq** [comment]
So I certainly did the locking/unlocking of the wallet, that did not help. How do you rescan the timechain starting blocks?

**Comment by theborakompanioni** [comment]
> So I certainly did the locking/unlocking of the wallet, that did not help. How do you rescan the timechain starting blocks?

Did you restart your node also?
Scanning the timechain should be available from the Setting view in the new version - v0.3.0.

**Comment by gimmanyq** [comment]
restarting the node did the trick
